-- ============================================================
--  NEXUS TECHHUB — Supabase PostgreSQL Schema (Target)
-- ============================================================

-- profiles
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  role VARCHAR(50) DEFAULT 'Customer' CHECK (role IN ('Admin', 'Manager', 'Customer')),
  email_opt_in BOOLEAN DEFAULT TRUE,
  sms_opt_in BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- audit_logs
CREATE TABLE public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action VARCHAR(255) NOT NULL,
  resource VARCHAR(255) NOT NULL,
  resource_id VARCHAR(255),
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- categories
CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  image VARCHAR(500),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- products
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  old_price DECIMAL(10,2),
  stock INT DEFAULT 0,
  sku VARCHAR(100) UNIQUE,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  image_url VARCHAR(500),
  featured BOOLEAN DEFAULT FALSE,
  new_arrival BOOLEAN DEFAULT FALSE,
  availability BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- orders
CREATE TABLE public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE RESTRICT,
  status VARCHAR(50) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Awaiting Payment', 'Paid', 'Processing', 'Shipped', 'Delivered', 'Cancelled', 'Refunded')),
  total_amount DECIMAL(10,2) NOT NULL,
  payment_status VARCHAR(50) DEFAULT 'unpaid',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- order_items
CREATE TABLE public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE RESTRICT,
  quantity INT DEFAULT 1,
  price DECIMAL(10,2) NOT NULL
);

-- wishlist
CREATE TABLE public.wishlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, product_id)
);

-- cart_items
CREATE TABLE public.cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  quantity INT DEFAULT 1,
  UNIQUE(user_id, product_id)
);

-- payments
CREATE TABLE public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE RESTRICT,
  user_id UUID REFERENCES public.profiles(id) ON DELETE RESTRICT,
  provider VARCHAR(50) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(10) DEFAULT 'KES',
  status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'paid', 'failed', 'cancelled', 'refunded')),
  transaction_reference VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- payment_logs
CREATE TABLE public.payment_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id BIGINT REFERENCES public.payments(id) ON DELETE CASCADE,
  provider VARCHAR(50) NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- PHASE 7: Business Features
-- ============================================================

-- coupons
CREATE TABLE public.coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) UNIQUE NOT NULL,
  discount_type VARCHAR(20) CHECK (discount_type IN ('percentage', 'fixed', 'free_shipping')),
  discount_value DECIMAL(10,2) NOT NULL,
  min_order_value DECIMAL(10,2) DEFAULT 0,
  usage_limit INT,
  used_count INT DEFAULT 0,
  active BOOLEAN DEFAULT TRUE,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- product_reviews
CREATE TABLE public.product_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  rating INT CHECK (rating BETWEEN 1 AND 5),
  review_text TEXT,
  verified_purchase BOOLEAN DEFAULT FALSE,
  status VARCHAR(20) DEFAULT 'published' CHECK (status IN ('published', 'hidden', 'flagged')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, product_id)
);

-- support_tickets
CREATE TABLE public.support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  subject VARCHAR(255) NOT NULL,
  status VARCHAR(20) DEFAULT 'open' CHECK (status IN ('open', 'pending', 'resolved', 'closed')),
  priority VARCHAR(20) DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ticket_messages
CREATE TABLE public.ticket_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- inventory_logs
CREATE TABLE public.inventory_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  change_amount INT NOT NULL,
  reason VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- invoices
CREATE TABLE public.invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE UNIQUE,
  invoice_number VARCHAR(100) UNIQUE NOT NULL,
  pdf_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

-- ============================================================
--  RBAC Helper Functions
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS VARCHAR AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid() LIMIT 1;
$$ LANGUAGE sql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
  SELECT public.get_my_role() = 'Admin';
$$ LANGUAGE sql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_manager()
RETURNS BOOLEAN AS $$
  SELECT public.get_my_role() = 'Manager';
$$ LANGUAGE sql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS BOOLEAN AS $$
  SELECT public.get_my_role() IN ('Admin', 'Manager');
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- ============================================================
--  Auth Triggers
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (new.id, new.email, COALESCE(new.raw_user_meta_data->>'full_name', 'User'), 'Customer');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
--  RLS Policies
-- ============================================================

-- audit_logs
CREATE POLICY "Admin read audit logs" ON public.audit_logs FOR SELECT USING (public.is_admin());
CREATE POLICY "Service insert audit logs" ON public.audit_logs FOR INSERT WITH CHECK (true);

-- profiles
-- Allow users to view their own profile  
CREATE POLICY "Customer can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
-- Allow users to update their own profile
CREATE POLICY "Customer can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- categories
CREATE POLICY "Public read categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Staff insert categories" ON public.categories FOR INSERT WITH CHECK (public.is_staff());
CREATE POLICY "Staff update categories" ON public.categories FOR UPDATE USING (public.is_staff());
CREATE POLICY "Admin delete categories" ON public.categories FOR DELETE USING (public.is_admin());

-- products
CREATE POLICY "Public read products" ON public.products FOR SELECT USING (availability = true OR public.is_staff());
CREATE POLICY "Staff insert products" ON public.products FOR INSERT WITH CHECK (public.is_staff());
CREATE POLICY "Staff update products" ON public.products FOR UPDATE USING (public.is_staff());
CREATE POLICY "Admin delete products" ON public.products FOR DELETE USING (public.is_admin());

-- orders
CREATE POLICY "Users read own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Staff read orders" ON public.orders FOR SELECT USING (public.is_staff());
CREATE POLICY "Staff update order status" ON public.orders FOR UPDATE USING (public.is_staff());
CREATE POLICY "Admin full orders" ON public.orders FOR ALL USING (public.is_admin());

-- order_items
CREATE POLICY "Users read own order items" ON public.order_items FOR SELECT USING (
  order_id IN (SELECT id FROM public.orders WHERE user_id = auth.uid() OR public.is_staff())
);
CREATE POLICY "Users insert own order items" ON public.order_items FOR INSERT WITH CHECK (
  order_id IN (SELECT id FROM public.orders WHERE user_id = auth.uid())
);

-- wishlist
CREATE POLICY "Users manage own wishlist" ON public.wishlist FOR ALL USING (auth.uid() = user_id);

-- cart_items
CREATE POLICY "Users manage own cart" ON public.cart_items FOR ALL USING (auth.uid() = user_id);

-- payments
CREATE POLICY "Users read own payments" ON public.payments FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Users insert own payments" ON public.payments FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "Staff read payments" ON public.payments FOR SELECT USING (public.is_staff());
CREATE POLICY "Admin full payments" ON public.payments FOR ALL USING (public.is_admin());

-- payment_logs
CREATE POLICY "Staff read payment logs" ON public.payment_logs FOR SELECT USING (public.is_staff());
CREATE POLICY "Service role full access logs" ON public.payment_logs FOR ALL USING (true); 

-- coupons
CREATE POLICY "Public read active coupons" ON public.coupons FOR SELECT USING (active = true);
CREATE POLICY "Admin manage coupons" ON public.coupons FOR ALL USING (public.is_admin());

-- product_reviews
CREATE POLICY "Public read published reviews" ON public.product_reviews FOR SELECT USING (status = 'published' OR auth.uid() = user_id OR public.is_staff());
CREATE POLICY "Users insert own reviews" ON public.product_reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own reviews" ON public.product_reviews FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Staff manage reviews" ON public.product_reviews FOR ALL USING (public.is_staff());

-- support_tickets
CREATE POLICY "Users read own tickets" ON public.support_tickets FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own tickets" ON public.support_tickets FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own tickets" ON public.support_tickets FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Staff full access tickets" ON public.support_tickets FOR ALL USING (public.is_staff());

-- ticket_messages
CREATE POLICY "Users read own ticket messages" ON public.ticket_messages FOR SELECT USING (
  ticket_id IN (SELECT id FROM public.support_tickets WHERE user_id = auth.uid()) OR public.is_staff()
);
CREATE POLICY "Users insert own ticket messages" ON public.ticket_messages FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Staff full access ticket messages" ON public.ticket_messages FOR ALL USING (public.is_staff());

-- inventory_logs
CREATE POLICY "Staff read inventory logs" ON public.inventory_logs FOR SELECT USING (public.is_staff());
CREATE POLICY "Staff insert inventory logs" ON public.inventory_logs FOR INSERT WITH CHECK (public.is_staff());

-- invoices
CREATE POLICY "Users read own invoices" ON public.invoices FOR SELECT USING (
  order_id IN (SELECT id FROM public.orders WHERE user_id = auth.uid()) OR public.is_staff()
);
CREATE POLICY "Service role insert invoices" ON public.invoices FOR INSERT WITH CHECK (true);
CREATE POLICY "Staff delete invoices" ON public.invoices FOR DELETE USING (public.is_staff());

-- ============================================================
--  Storage Policies (product_images)
-- ============================================================
-- To apply these, ensure `storage` schema is accessible. If using raw SQL on Supabase dashboard:
-- CREATE POLICY "Public read product images" ON storage.objects FOR SELECT USING (bucket_id = 'product_images');
-- CREATE POLICY "Staff upload product images" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'product_images' AND public.is_staff());
-- CREATE POLICY "Staff update product images" ON storage.objects FOR UPDATE USING (bucket_id = 'product_images' AND public.is_staff());
-- ============================================================
--  Security Triggers (Prevent Privilege Escalation)
-- ============================================================
CREATE OR REPLACE FUNCTION public.prevent_role_escalation()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.role IS DISTINCT FROM OLD.role THEN
    IF NOT public.is_admin() THEN
      RAISE EXCEPTION 'Unauthorized: Only Admins can change roles.';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS check_role_escalation ON public.profiles;
CREATE TRIGGER check_role_escalation
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.prevent_role_escalation();

-- ============================================================
--  Audit Log Triggers
-- ============================================================
CREATE OR REPLACE FUNCTION public.log_audit_event()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.audit_logs (user_id, action, resource, resource_id, metadata)
    VALUES (auth.uid(), 'CREATE', TG_TABLE_NAME, NEW.id::text, row_to_json(NEW)::jsonb);
    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO public.audit_logs (user_id, action, resource, resource_id, metadata)
    VALUES (auth.uid(), 'UPDATE', TG_TABLE_NAME, NEW.id::text, jsonb_build_object('old', row_to_json(OLD), 'new', row_to_json(NEW)));
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO public.audit_logs (user_id, action, resource, resource_id, metadata)
    VALUES (auth.uid(), 'DELETE', TG_TABLE_NAME, OLD.id::text, row_to_json(OLD)::jsonb);
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Apply audit triggers to critical tables
CREATE TRIGGER audit_products_trigger AFTER INSERT OR UPDATE OR DELETE ON public.products FOR EACH ROW EXECUTE FUNCTION public.log_audit_event();
CREATE TRIGGER audit_orders_trigger AFTER UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.log_audit_event();
CREATE TRIGGER audit_profiles_trigger AFTER UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.log_audit_event();
