-- ============================================================
--  NEXUS TECHHUB — Migration 001: Missing Columns & Tables
--  Run this in your Supabase SQL Editor to sync schema with frontend
-- ============================================================

-- ─── orders: add shipping + payment fields ───────────────────────────────────
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS shipping_name    VARCHAR(255),
  ADD COLUMN IF NOT EXISTS shipping_phone   VARCHAR(50),
  ADD COLUMN IF NOT EXISTS shipping_address TEXT,
  ADD COLUMN IF NOT EXISTS shipping_city    VARCHAR(100),
  ADD COLUMN IF NOT EXISTS shipping_postal_code VARCHAR(20),
  ADD COLUMN IF NOT EXISTS payment_method   VARCHAR(50),
  ADD COLUMN IF NOT EXISTS notes            TEXT;

-- ─── products: add missing fields used by frontend ───────────────────────────
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS brand      VARCHAR(255),
  ADD COLUMN IF NOT EXISTS short_desc TEXT;

-- ─── profiles: add avatar + status fields ────────────────────────────────────
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500),
  ADD COLUMN IF NOT EXISTS status     VARCHAR(20) DEFAULT 'approved'
    CHECK (status IN ('approved', 'suspended', 'pending'));

-- ─── newsletter_subscribers ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR(255) UNIQUE NOT NULL,
  subscribed_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for newsletter_subscribers
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "Anyone can subscribe"
  ON public.newsletter_subscribers FOR INSERT
  WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "Admins can view subscribers"
  ON public.newsletter_subscribers FOR SELECT
  USING (get_my_role() IN ('Admin', 'Manager'));

CREATE POLICY IF NOT EXISTS "Admins can delete subscribers"
  ON public.newsletter_subscribers FOR DELETE
  USING (get_my_role() = 'Admin');

-- ─── support_tickets ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.support_tickets (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  name        VARCHAR(255) NOT NULL,
  email       VARCHAR(255) NOT NULL,
  subject     VARCHAR(500) NOT NULL,
  message     TEXT NOT NULL,
  status      VARCHAR(50) DEFAULT 'open'
              CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for support_tickets
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "Anyone can submit a ticket"
  ON public.support_tickets FOR INSERT
  WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "Users can view own tickets"
  ON public.support_tickets FOR SELECT
  USING (auth.uid() = user_id OR get_my_role() IN ('Admin', 'Manager'));

CREATE POLICY IF NOT EXISTS "Admins can update tickets"
  ON public.support_tickets FOR UPDATE
  USING (get_my_role() IN ('Admin', 'Manager'));

-- ─── product_reviews ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.product_reviews (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  rating      INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title       VARCHAR(255),
  body        TEXT,
  approved    BOOLEAN DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(product_id, user_id)
);

-- RLS for product_reviews
ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "Anyone can view approved reviews"
  ON public.product_reviews FOR SELECT
  USING (approved = true OR auth.uid() = user_id OR get_my_role() IN ('Admin', 'Manager'));

CREATE POLICY IF NOT EXISTS "Authenticated users can submit reviews"
  ON public.product_reviews FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL AND auth.uid() = user_id);

CREATE POLICY IF NOT EXISTS "Users can update own reviews"
  ON public.product_reviews FOR UPDATE
  USING (auth.uid() = user_id OR get_my_role() IN ('Admin', 'Manager'));

CREATE POLICY IF NOT EXISTS "Users can delete own reviews"
  ON public.product_reviews FOR DELETE
  USING (auth.uid() = user_id OR get_my_role() = 'Admin');

-- ─── settings ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.settings (
  key        VARCHAR(255) PRIMARY KEY,
  value      TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for settings
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "Anyone can read settings"
  ON public.settings FOR SELECT
  USING (true);

CREATE POLICY IF NOT EXISTS "Admins can update settings"
  ON public.settings FOR ALL
  USING (get_my_role() = 'Admin');

-- Seed default settings
INSERT INTO public.settings (key, value) VALUES
  ('store_name',           'NexusTech Hub'),
  ('contact_email',        'support@nexustechhub.com'),
  ('contact_phone',        '+254 728 097 596'),
  ('currency',             'KES'),
  ('theme_primary_color',  '#FF724C'),
  ('tax_rate',             '0'),
  ('shipping_fee',         '0')
ON CONFLICT (key) DO NOTHING;

-- ─── Performance indexes ──────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_orders_user_id    ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status     ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cart_items_user   ON public.cart_items(user_id);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_featured ON public.products(featured);
CREATE INDEX IF NOT EXISTS idx_reviews_product   ON public.product_reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user      ON public.product_reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_tickets_email     ON public.support_tickets(email);
CREATE INDEX IF NOT EXISTS idx_tickets_status    ON public.support_tickets(status);

-- ─── update_updated_at trigger ───────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_support_tickets_updated_at
  BEFORE UPDATE ON public.support_tickets
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE TRIGGER trg_product_reviews_updated_at
  BEFORE UPDATE ON public.product_reviews
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
