-- ============================================================
--  NEXUS TECHHUB — Migration 005: Enterprise Payment Readiness
--  Idempotency, Transactions, Audit Logging, & Schema Patches
-- ============================================================

-- ============================================================
-- 1. SCHEMA CORRECTIONS (BIGINT FKeys)
-- ============================================================
-- The orders and payments tables use BIGINT ids. 
-- Fix the foreign keys introduced in migration 004 to match.

ALTER TABLE public.payment_callbacks DROP CONSTRAINT IF EXISTS payment_callbacks_payment_id_fkey;
ALTER TABLE public.payment_callbacks ALTER COLUMN payment_id TYPE BIGINT USING NULL;
ALTER TABLE public.payment_callbacks ADD CONSTRAINT payment_callbacks_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id) ON DELETE CASCADE;

ALTER TABLE public.refunds DROP CONSTRAINT IF EXISTS refunds_payment_id_fkey;
ALTER TABLE public.refunds DROP CONSTRAINT IF EXISTS refunds_order_id_fkey;
ALTER TABLE public.refunds ALTER COLUMN payment_id TYPE BIGINT USING NULL;
ALTER TABLE public.refunds ALTER COLUMN order_id TYPE BIGINT USING NULL;
ALTER TABLE public.refunds ADD CONSTRAINT refunds_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id) ON DELETE CASCADE;
ALTER TABLE public.refunds ADD CONSTRAINT refunds_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;

ALTER TABLE public.inventory_logs DROP CONSTRAINT IF EXISTS inventory_logs_order_id_fkey;
ALTER TABLE public.inventory_logs DROP CONSTRAINT IF EXISTS inventory_logs_product_id_fkey;
ALTER TABLE public.inventory_logs ALTER COLUMN order_id TYPE BIGINT USING NULL;
ALTER TABLE public.inventory_logs ALTER COLUMN product_id TYPE BIGINT USING NULL;
ALTER TABLE public.inventory_logs ADD CONSTRAINT inventory_logs_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE SET NULL;
ALTER TABLE public.inventory_logs ADD CONSTRAINT inventory_logs_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;

-- Add idempotency marker to callbacks
ALTER TABLE public.payment_callbacks ADD COLUMN IF NOT EXISTS processed BOOLEAN DEFAULT false;

-- Add attempt tracking to payments
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS attempt_number INT DEFAULT 1;

-- Ensure payment_logs table exists and matches requirements
CREATE TABLE IF NOT EXISTS public.payment_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id BIGINT REFERENCES public.payments(id) ON DELETE CASCADE,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
  event_type VARCHAR(100) NOT NULL,
  provider VARCHAR(50),
  description TEXT,
  payload JSONB,
  ip_address VARCHAR(45),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 2. AUTOMATIC AUDIT LOGGING (PostgreSQL Triggers)
-- ============================================================
CREATE OR REPLACE FUNCTION log_payment_status_changes()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') OR (TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status) THEN
    INSERT INTO public.payment_logs (payment_id, order_id, event_type, provider, description)
    VALUES (
      NEW.id,
      NEW.order_id,
      CASE 
        WHEN TG_OP = 'INSERT' THEN 'payment_initiated'
        WHEN NEW.status = 'paid' THEN 'payment_verified'
        WHEN NEW.status = 'failed' THEN 'payment_failed'
        WHEN NEW.status = 'cancelled' THEN 'payment_cancelled'
        ELSE 'status_changed_' || NEW.status
      END,
      NEW.provider,
      'Payment status updated to: ' || NEW.status
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_payment_audit_log ON public.payments;
CREATE TRIGGER trigger_payment_audit_log
  AFTER INSERT OR UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION log_payment_status_changes();

-- ============================================================
-- 3. ATOMIC CALLBACK PROCESSING (PL/pgSQL RPC)
-- ============================================================
-- Processes a M-Pesa callback atomically. If any step fails, everything rolls back.
CREATE OR REPLACE FUNCTION process_mpesa_callback(
  p_checkout_request_id VARCHAR,
  p_merchant_request_id VARCHAR,
  p_result_code INT,
  p_result_desc TEXT,
  p_amount NUMERIC,
  p_receipt VARCHAR,
  p_phone VARCHAR,
  p_raw_payload JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_payment RECORD;
  v_order RECORD;
  v_item RECORD;
  v_callback_id UUID;
  v_is_success BOOLEAN;
  v_payment_status VARCHAR;
BEGIN
  v_is_success := (p_result_code = 0);
  v_payment_status := CASE WHEN v_is_success THEN 'paid' ELSE 'failed' END;

  -- 1. Check idempotency: Have we seen this callback before?
  IF EXISTS (SELECT 1 FROM public.payment_callbacks WHERE checkout_request_id = p_checkout_request_id AND processed = true) THEN
    -- Log duplicate attempt but return success to Safaricom
    INSERT INTO public.payment_logs (event_type, provider, description, payload)
    VALUES ('duplicate_callback_ignored', 'mpesa', 'Ignored duplicate callback for ' || p_checkout_request_id, p_raw_payload);
    
    RETURN jsonb_build_object('success', true, 'message', 'Duplicate callback ignored');
  END IF;

  -- 2. Lock Payment Row
  SELECT * INTO v_payment FROM public.payments WHERE transaction_reference = p_checkout_request_id FOR UPDATE;
  
  IF v_payment IS NULL THEN
    -- Store orphan callback
    INSERT INTO public.payment_callbacks (checkout_request_id, merchant_request_id, result_code, result_desc, raw_payload, processed)
    VALUES (p_checkout_request_id, p_merchant_request_id, p_result_code, p_result_desc, p_raw_payload, true);
    
    RETURN jsonb_build_object('success', false, 'error', 'Payment intent not found for reference ' || p_checkout_request_id);
  END IF;

  -- 3. Lock Order Row
  SELECT * INTO v_order FROM public.orders WHERE id = v_payment.order_id FOR UPDATE;

  -- 4. Insert/Update Callback Record
  INSERT INTO public.payment_callbacks (
    payment_id, checkout_request_id, merchant_request_id, result_code, result_desc, amount, mpesa_receipt, phone_number, raw_payload, processed
  ) VALUES (
    v_payment.id, p_checkout_request_id, p_merchant_request_id, p_result_code, p_result_desc, p_amount, p_receipt, p_phone, p_raw_payload, true
  )
  ON CONFLICT (checkout_request_id) DO UPDATE SET
    merchant_request_id = EXCLUDED.merchant_request_id,
    result_code = EXCLUDED.result_code,
    result_desc = EXCLUDED.result_desc,
    amount = EXCLUDED.amount,
    mpesa_receipt = EXCLUDED.mpesa_receipt,
    phone_number = EXCLUDED.phone_number,
    raw_payload = EXCLUDED.raw_payload,
    processed = true
  RETURNING id INTO v_callback_id;

  -- 5. Update Payment Status (Triggers will handle logging)
  UPDATE public.payments SET status = v_payment_status, updated_at = NOW() WHERE id = v_payment.id;

  -- 6. Update Order Status
  UPDATE public.orders 
  SET 
    payment_status = v_payment_status, 
    status = CASE WHEN v_is_success THEN 'Processing' ELSE status END
  WHERE id = v_order.id;

  -- 7. Deduct Inventory & Create Notifications if successful
  IF v_is_success THEN
    FOR v_item IN (SELECT product_id, quantity FROM public.order_items WHERE order_id = v_order.id) LOOP
      -- Create Inventory Log
      INSERT INTO public.inventory_logs (product_id, order_id, change_amount, reason, notes)
      VALUES (v_item.product_id, v_order.id, -v_item.quantity, 'sale', 'M-Pesa payment verified');
      
      -- Deduct Product Stock (Do not allow negative stock)
      UPDATE public.products 
      SET stock = GREATEST(0, stock - v_item.quantity)
      WHERE id = v_item.product_id;
    END LOOP;

    -- Notification (Customer)
    IF v_payment.user_id IS NOT NULL THEN
      INSERT INTO public.notifications (user_id, title, message, type)
      VALUES (v_payment.user_id, 'Payment Received', 'We received your payment of KES ' || p_amount || ' for Order ' || v_order.id || '. Thank you!', 'success');
    END IF;
    
    -- Notification (Admin)
    -- Assuming admin role notifications can be broadcast or we query admin users. 
    -- We skip broad insert for now and rely on realtime dashboard alerts, or a generic 'admin' topic.
  END IF;

  RETURN jsonb_build_object('success', true, 'message', 'Callback processed idempotently');
EXCEPTION
  WHEN OTHERS THEN
    -- If any error occurs, the transaction rolls back automatically
    INSERT INTO public.payment_logs (event_type, description, payload)
    VALUES ('callback_processing_error', SQLERRM, p_raw_payload);
    
    RAISE EXCEPTION 'Callback processing failed: %', SQLERRM;
END;
$$;

-- ============================================================
-- 4. EXPIRATION FUNCTION
-- ============================================================
-- Call this periodically via pg_cron or Edge Function to expire stale requests
CREATE OR REPLACE FUNCTION expire_pending_payments(p_minutes_timeout INT DEFAULT 30)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_expired_count INT := 0;
  v_payment RECORD;
BEGIN
  FOR v_payment IN (
    SELECT id, order_id FROM public.payments 
    WHERE status = 'pending' AND created_at < NOW() - (p_minutes_timeout || ' minutes')::INTERVAL
  ) LOOP
    -- Mark payment expired
    UPDATE public.payments SET status = 'failed' WHERE id = v_payment.id;
    
    -- Log
    INSERT INTO public.payment_logs (payment_id, order_id, event_type, description)
    VALUES (v_payment.id, v_payment.order_id, 'payment_expired', 'Payment timed out after ' || p_minutes_timeout || ' minutes.');
    
    v_expired_count := v_expired_count + 1;
  END LOOP;
  
  RETURN v_expired_count;
END;
$$;

-- ============================================================
-- 5. PERFORMANCE INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_payments_status_created ON public.payments(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_payment_logs_payment_id ON public.payment_logs(payment_id);
CREATE INDEX IF NOT EXISTS idx_payment_logs_created ON public.payment_logs(created_at DESC);
