-- ============================================================
--  NEXUS TECHHUB — ERP Business Modules Migration
--  Migration: 006_erp_modules.sql
--  Run this in your Supabase SQL Editor
-- ============================================================

-- ── Step 1: Extend role CHECK constraint ──────────────────────
ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_role_check;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_role_check
  CHECK (role IN (
    'Admin',
    'super_admin',
    'Manager',
    'Customer',
    'Warehouse_Staff',
    'Finance_Officer',
    'Dispatch_Officer',
    'Driver'
  ));

-- ── Step 2: Suppliers ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.suppliers (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(255) NOT NULL,
  contact_person VARCHAR(255),
  phone         VARCHAR(50),
  email         VARCHAR(255),
  company       VARCHAR(255),
  address       TEXT,
  city          VARCHAR(100),
  country       VARCHAR(100) DEFAULT 'Kenya',
  tax_number    VARCHAR(100),
  website       VARCHAR(255),
  notes         TEXT,
  status        VARCHAR(20)  DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'inactive')),
  rating        DECIMAL(3,2) DEFAULT 5.00,
  created_at    TIMESTAMPTZ  DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  DEFAULT NOW()
);

-- ── Step 3: Drivers ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.drivers (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name       VARCHAR(255) NOT NULL,
  phone           VARCHAR(50)  NOT NULL,
  email           VARCHAR(255),
  national_id     VARCHAR(100),
  vehicle_number  VARCHAR(50),
  vehicle_type    VARCHAR(100),
  license_number  VARCHAR(100),
  photo_url       TEXT,
  status          VARCHAR(20)  DEFAULT 'available' CHECK (status IN ('available', 'busy', 'offline', 'suspended')),
  rating          DECIMAL(3,2) DEFAULT 5.00,
  total_deliveries INT         DEFAULT 0,
  notes           TEXT,
  created_at      TIMESTAMPTZ  DEFAULT NOW(),
  updated_at      TIMESTAMPTZ  DEFAULT NOW()
);

-- ── Step 4: Dispatches ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.dispatches (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dispatch_number     VARCHAR(50) UNIQUE NOT NULL,
  order_id            BIGINT REFERENCES public.orders(id) ON DELETE RESTRICT,
  driver_id           BIGINT REFERENCES public.drivers(id) ON DELETE SET NULL,
  assigned_by         UUID   REFERENCES public.profiles(id) ON DELETE SET NULL,
  delivery_address    TEXT,
  customer_name       VARCHAR(255),
  customer_phone      VARCHAR(50),
  vehicle             VARCHAR(100),
  dispatch_date       DATE,
  estimated_delivery  DATE,
  actual_delivery     TIMESTAMPTZ,
  status              VARCHAR(20) DEFAULT 'pending'
                      CHECK (status IN ('pending','assigned','picked_up','in_transit','delivered','failed','returned')),
  notes               TEXT,
  delivery_notes      TEXT,
  failed_reason       TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-generate dispatch_number
CREATE OR REPLACE FUNCTION public.generate_dispatch_number()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.dispatch_number IS NULL OR NEW.dispatch_number = '' THEN
    NEW.dispatch_number := 'DSP-' || TO_CHAR(NOW(), 'YYYYMMDD') || '-' || LPAD(NEW.id::text, 4, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_dispatch_number ON public.dispatches;
CREATE TRIGGER set_dispatch_number
  BEFORE INSERT ON public.dispatches
  FOR EACH ROW EXECUTE FUNCTION public.generate_dispatch_number();

-- ── Step 5: Enhanced Inventory ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.inventory (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id      BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  supplier_id     BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
  sku             VARCHAR(100),
  quantity_on_hand  INT DEFAULT 0,
  quantity_reserved INT DEFAULT 0,
  reorder_level   INT DEFAULT 10,
  reorder_quantity INT DEFAULT 50,
  cost_price      DECIMAL(10,2),
  location        VARCHAR(100),
  last_restocked  TIMESTAMPTZ,
  notes           TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (product_id)
);

-- ── Step 6: Stock Movements ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public.stock_movements (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id      BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  inventory_id    BIGINT REFERENCES public.inventory(id) ON DELETE CASCADE,
  user_id         UUID   REFERENCES public.profiles(id) ON DELETE SET NULL,
  supplier_id     BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
  order_id        BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
  movement_type   VARCHAR(30) NOT NULL
                  CHECK (movement_type IN ('purchase','sale','return','damage','adjustment','transfer')),
  quantity        INT NOT NULL,
  quantity_before INT NOT NULL DEFAULT 0,
  quantity_after  INT NOT NULL DEFAULT 0,
  unit_cost       DECIMAL(10,2),
  reference       VARCHAR(255),
  notes           TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── Step 7: Transactions (Finance Ledger) ─────────────────────
CREATE TABLE IF NOT EXISTS public.transactions (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type            VARCHAR(20) NOT NULL CHECK (type IN ('income','expense')),
  category        VARCHAR(100),
  description     TEXT NOT NULL,
  amount          DECIMAL(12,2) NOT NULL,
  currency        VARCHAR(10) DEFAULT 'KES',
  payment_method  VARCHAR(50)
                  CHECK (payment_method IN ('cash','mpesa','paypal','flutterwave','bank_transfer','cheque','other')),
  reference       VARCHAR(255),
  order_id        BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
  user_id         UUID   REFERENCES public.profiles(id) ON DELETE SET NULL,
  supplier_id     BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
  status          VARCHAR(20) DEFAULT 'completed'
                  CHECK (status IN ('pending','completed','cancelled','reversed')),
  transaction_date DATE DEFAULT CURRENT_DATE,
  notes           TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── Step 8: Expenses (detailed) ───────────────────────────────
CREATE TABLE IF NOT EXISTS public.expenses (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category        VARCHAR(100) NOT NULL,
  description     TEXT NOT NULL,
  amount          DECIMAL(12,2) NOT NULL,
  payment_method  VARCHAR(50),
  supplier_id     BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
  receipt_url     TEXT,
  expense_date    DATE DEFAULT CURRENT_DATE,
  approved_by     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  status          VARCHAR(20) DEFAULT 'approved'
                  CHECK (status IN ('pending','approved','rejected')),
  notes           TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── Step 9: Bank Accounts ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.bank_accounts (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_name    VARCHAR(255) NOT NULL,
  bank_name       VARCHAR(255) NOT NULL,
  account_number  VARCHAR(100),
  account_type    VARCHAR(50) CHECK (account_type IN ('current','savings','mpesa','paypal','other')),
  currency        VARCHAR(10) DEFAULT 'KES',
  balance         DECIMAL(14,2) DEFAULT 0,
  is_default      BOOLEAN DEFAULT FALSE,
  notes           TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── Step 10: Supplier Products junction ───────────────────────
CREATE TABLE IF NOT EXISTS public.supplier_products (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id     BIGINT REFERENCES public.suppliers(id) ON DELETE CASCADE,
  product_id      BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  unit_cost       DECIMAL(10,2),
  lead_time_days  INT DEFAULT 7,
  is_primary      BOOLEAN DEFAULT FALSE,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(supplier_id, product_id)
);

-- ============================================================
--  Enable RLS on all new tables
-- ============================================================
ALTER TABLE public.suppliers          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drivers            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dispatches         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bank_accounts      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_products  ENABLE ROW LEVEL SECURITY;

-- ============================================================
--  RBAC Helper Functions (extend existing)
-- ============================================================
CREATE OR REPLACE FUNCTION public.is_warehouse_staff()
RETURNS BOOLEAN AS $$
  SELECT public.get_my_role() IN ('Admin', 'Manager', 'Warehouse_Staff');
$$ LANGUAGE sql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_finance_officer()
RETURNS BOOLEAN AS $$
  SELECT public.get_my_role() IN ('Admin', 'Finance_Officer');
$$ LANGUAGE sql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_dispatch_officer()
RETURNS BOOLEAN AS $$
  SELECT public.get_my_role() IN ('Admin', 'Manager', 'Dispatch_Officer');
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- ============================================================
--  RLS Policies — Suppliers
-- ============================================================
CREATE POLICY "Staff read suppliers"    ON public.suppliers FOR SELECT USING (public.is_staff());
CREATE POLICY "Staff insert suppliers"  ON public.suppliers FOR INSERT WITH CHECK (public.is_staff());
CREATE POLICY "Staff update suppliers"  ON public.suppliers FOR UPDATE USING (public.is_staff());
CREATE POLICY "Admin delete suppliers"  ON public.suppliers FOR DELETE USING (public.is_admin());

-- ============================================================
--  RLS Policies — Drivers
-- ============================================================
CREATE POLICY "Dispatch read drivers"   ON public.drivers FOR SELECT USING (public.is_dispatch_officer());
CREATE POLICY "Admin manage drivers"    ON public.drivers FOR ALL USING (public.is_admin());
CREATE POLICY "Staff insert drivers"    ON public.drivers FOR INSERT WITH CHECK (public.is_staff());
CREATE POLICY "Staff update drivers"    ON public.drivers FOR UPDATE USING (public.is_staff());

-- ============================================================
--  RLS Policies — Dispatches
-- ============================================================
CREATE POLICY "Dispatch read dispatches"  ON public.dispatches FOR SELECT USING (public.is_dispatch_officer());
CREATE POLICY "Dispatch insert dispatch"  ON public.dispatches FOR INSERT WITH CHECK (public.is_dispatch_officer());
CREATE POLICY "Dispatch update dispatch"  ON public.dispatches FOR UPDATE USING (public.is_dispatch_officer());
CREATE POLICY "Admin delete dispatch"     ON public.dispatches FOR DELETE USING (public.is_admin());

-- ============================================================
--  RLS Policies — Inventory
-- ============================================================
CREATE POLICY "Warehouse read inventory"   ON public.inventory FOR SELECT USING (public.is_warehouse_staff());
CREATE POLICY "Warehouse insert inventory" ON public.inventory FOR INSERT WITH CHECK (public.is_warehouse_staff());
CREATE POLICY "Warehouse update inventory" ON public.inventory FOR UPDATE USING (public.is_warehouse_staff());
CREATE POLICY "Admin delete inventory"     ON public.inventory FOR DELETE USING (public.is_admin());

-- ============================================================
--  RLS Policies — Stock Movements
-- ============================================================
CREATE POLICY "Warehouse read movements"   ON public.stock_movements FOR SELECT USING (public.is_warehouse_staff());
CREATE POLICY "Warehouse insert movements" ON public.stock_movements FOR INSERT WITH CHECK (public.is_warehouse_staff());

-- ============================================================
--  RLS Policies — Transactions
-- ============================================================
CREATE POLICY "Finance read transactions"   ON public.transactions FOR SELECT USING (public.is_finance_officer() OR public.is_admin());
CREATE POLICY "Finance insert transactions" ON public.transactions FOR INSERT WITH CHECK (public.is_finance_officer() OR public.is_admin());
CREATE POLICY "Finance update transactions" ON public.transactions FOR UPDATE USING (public.is_finance_officer() OR public.is_admin());
CREATE POLICY "Admin delete transactions"   ON public.transactions FOR DELETE USING (public.is_admin());

-- ============================================================
--  RLS Policies — Expenses
-- ============================================================
CREATE POLICY "Finance read expenses"   ON public.expenses FOR SELECT USING (public.is_finance_officer() OR public.is_admin());
CREATE POLICY "Finance insert expenses" ON public.expenses FOR INSERT WITH CHECK (public.is_finance_officer() OR public.is_admin());
CREATE POLICY "Admin delete expenses"   ON public.expenses FOR DELETE USING (public.is_admin());

-- ============================================================
--  RLS Policies — Bank Accounts
-- ============================================================
CREATE POLICY "Finance read accounts"   ON public.bank_accounts FOR SELECT USING (public.is_finance_officer() OR public.is_admin());
CREATE POLICY "Admin manage accounts"   ON public.bank_accounts FOR ALL USING (public.is_admin());

-- ============================================================
--  RLS Policies — Supplier Products
-- ============================================================
CREATE POLICY "Staff read supplier_products"   ON public.supplier_products FOR SELECT USING (public.is_staff());
CREATE POLICY "Staff insert supplier_products" ON public.supplier_products FOR INSERT WITH CHECK (public.is_staff());
CREATE POLICY "Admin delete supplier_products" ON public.supplier_products FOR DELETE USING (public.is_admin());

-- ============================================================
--  Updated_at triggers
-- ============================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER suppliers_updated_at   BEFORE UPDATE ON public.suppliers   FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER drivers_updated_at     BEFORE UPDATE ON public.drivers     FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER dispatches_updated_at  BEFORE UPDATE ON public.dispatches  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER inventory_updated_at   BEFORE UPDATE ON public.inventory   FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER transactions_updated_at BEFORE UPDATE ON public.transactions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER bank_accounts_updated_at BEFORE UPDATE ON public.bank_accounts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
--  Audit triggers for ERP tables
-- ============================================================
CREATE TRIGGER audit_suppliers_trigger
  AFTER INSERT OR UPDATE OR DELETE ON public.suppliers
  FOR EACH ROW EXECUTE FUNCTION public.log_audit_event();

CREATE TRIGGER audit_drivers_trigger
  AFTER INSERT OR UPDATE OR DELETE ON public.drivers
  FOR EACH ROW EXECUTE FUNCTION public.log_audit_event();

CREATE TRIGGER audit_dispatches_trigger
  AFTER INSERT OR UPDATE ON public.dispatches
  FOR EACH ROW EXECUTE FUNCTION public.log_audit_event();

-- ============================================================
--  Driver status sync trigger
--  When a dispatch is assigned → driver becomes busy
--  When delivered/failed/returned → driver becomes available
-- ============================================================
CREATE OR REPLACE FUNCTION public.sync_driver_status()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.driver_id IS NOT NULL THEN
    IF NEW.status IN ('assigned', 'picked_up', 'in_transit') THEN
      UPDATE public.drivers SET status = 'busy' WHERE id = NEW.driver_id;
    ELSIF NEW.status IN ('delivered', 'failed', 'returned') THEN
      UPDATE public.drivers SET status = 'available', total_deliveries = total_deliveries + 1
      WHERE id = NEW.driver_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS sync_driver_status_trigger ON public.dispatches;
CREATE TRIGGER sync_driver_status_trigger
  AFTER INSERT OR UPDATE OF status ON public.dispatches
  FOR EACH ROW EXECUTE FUNCTION public.sync_driver_status();

-- ============================================================
--  Seed default bank account
-- ============================================================
INSERT INTO public.bank_accounts (account_name, bank_name, account_type, currency, is_default)
VALUES ('Main Cash Account', 'NexusTech', 'current', 'KES', TRUE)
ON CONFLICT DO NOTHING;

-- ============================================================
--  Enable Realtime on new tables
-- ============================================================
ALTER PUBLICATION supabase_realtime ADD TABLE public.dispatches;
ALTER PUBLICATION supabase_realtime ADD TABLE public.drivers;
ALTER PUBLICATION supabase_realtime ADD TABLE public.inventory;
ALTER PUBLICATION supabase_realtime ADD TABLE public.transactions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.suppliers;
