-- ============================================================
--  NEXUS TECHHUB — Multi-Portal ERP Migration
--  Migration: 007_multi_portal.sql
--  Run this in your Supabase SQL Editor AFTER 006_erp_modules.sql
-- ============================================================

-- ── Step 1: Extend role CHECK to include Supplier + Manager ────
ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_role_check;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_role_check
  CHECK (role IN (
    'Admin',
    'super_admin',
    'Manager',
    'Customer',
    'Warehouse_Staff',
    'Finance_Officer',
    'Dispatch_Officer',
    'Driver',
    'Supplier'
  ));

-- ── Step 2: Extend profiles with enterprise columns ────────────
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS employee_number  VARCHAR(50),
  ADD COLUMN IF NOT EXISTS department       VARCHAR(100),
  ADD COLUMN IF NOT EXISTS branch           VARCHAR(100),
  ADD COLUMN IF NOT EXISTS status           VARCHAR(20) DEFAULT 'active'
    CHECK (status IN ('active', 'inactive', 'suspended')),
  ADD COLUMN IF NOT EXISTS last_login       TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS phone            VARCHAR(50),
  ADD COLUMN IF NOT EXISTS company_name     VARCHAR(255),
  ADD COLUMN IF NOT EXISTS contact_person   VARCHAR(255),
  ADD COLUMN IF NOT EXISTS tax_number       VARCHAR(100);

-- ── Step 3: Link drivers table to auth users ───────────────────
ALTER TABLE public.drivers
  ADD COLUMN IF NOT EXISTS user_id  UUID REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE UNIQUE INDEX IF NOT EXISTS drivers_user_id_unique
  ON public.drivers (user_id)
  WHERE user_id IS NOT NULL;

-- ── Step 4: Link suppliers table to auth users ─────────────────
ALTER TABLE public.suppliers
  ADD COLUMN IF NOT EXISTS user_id  UUID REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE UNIQUE INDEX IF NOT EXISTS suppliers_user_id_unique
  ON public.suppliers (user_id)
  WHERE user_id IS NOT NULL;

-- ── Step 5: Portal audit logs ──────────────────────────────────
CREATE TABLE IF NOT EXISTS public.portal_audit_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID          NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  portal      VARCHAR(50)   NOT NULL, -- 'admin'|'dispatch'|'driver'|'inventory'|'finance'|'supplier'
  action      VARCHAR(255)  NOT NULL,
  resource    VARCHAR(255),
  ip_address  VARCHAR(50),
  user_agent  TEXT,
  meta        JSONB,
  created_at  TIMESTAMPTZ   DEFAULT NOW()
);

ALTER TABLE public.portal_audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can view all audit logs"
  ON public.portal_audit_logs FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid()
      AND role IN ('Admin', 'super_admin')
    )
  );

CREATE POLICY "Users can insert their own audit logs"
  ON public.portal_audit_logs FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- ── Step 6: Portal notifications table ────────────────────────
CREATE TABLE IF NOT EXISTS public.portal_notifications (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID          NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  portal      VARCHAR(50)   NOT NULL,
  title       VARCHAR(255)  NOT NULL,
  message     TEXT,
  type        VARCHAR(50)   DEFAULT 'info' CHECK (type IN ('info','success','warning','error')),
  is_read     BOOLEAN       DEFAULT FALSE,
  action_url  TEXT,
  created_at  TIMESTAMPTZ   DEFAULT NOW()
);

ALTER TABLE public.portal_notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own notifications"
  ON public.portal_notifications FOR ALL
  USING (user_id = auth.uid());

CREATE POLICY "Service role can insert notifications"
  ON public.portal_notifications FOR INSERT
  WITH CHECK (TRUE);

-- ── Step 7: Update last_login via trigger ─────────────────────
CREATE OR REPLACE FUNCTION public.update_last_login()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE public.profiles SET last_login = NOW() WHERE id = NEW.id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_sign_in ON auth.sessions;

-- ── Step 8: RLS helper — driver can see own dispatches ─────────
CREATE OR REPLACE FUNCTION public.get_driver_id_for_user()
RETURNS BIGINT LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT id FROM public.drivers WHERE user_id = auth.uid() LIMIT 1;
$$;

-- Update dispatches RLS: drivers see only their assigned dispatches
DROP POLICY IF EXISTS "Drivers can view their dispatches" ON public.dispatches;
CREATE POLICY "Drivers can view their dispatches"
  ON public.dispatches FOR SELECT
  USING (
    driver_id = public.get_driver_id_for_user()
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid()
      AND role IN ('Admin', 'super_admin', 'Manager', 'Dispatch_Officer')
    )
  );

-- ── Step 9: RLS helper — supplier can see own records ─────────
CREATE OR REPLACE FUNCTION public.get_supplier_id_for_user()
RETURNS BIGINT LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT id FROM public.suppliers WHERE user_id = auth.uid() LIMIT 1;
$$;

-- Suppliers can view their own POs / supplier_products
DROP POLICY IF EXISTS "Suppliers can view their products" ON public.supplier_products;
CREATE POLICY "Suppliers can view their products"
  ON public.supplier_products FOR SELECT
  USING (
    supplier_id = public.get_supplier_id_for_user()
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid()
      AND role IN ('Admin', 'super_admin', 'Manager', 'Warehouse_Staff', 'Finance_Officer')
    )
  );

-- ── Step 10: Finance RLS — only Finance Officers + Admins ──────
DROP POLICY IF EXISTS "Finance officers can access transactions" ON public.transactions;
CREATE POLICY "Finance officers can access transactions"
  ON public.transactions FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid()
      AND role IN ('Admin', 'super_admin', 'Finance_Officer')
    )
  );

DROP POLICY IF EXISTS "Finance officers can access expenses" ON public.expenses;
CREATE POLICY "Finance officers can access expenses"
  ON public.expenses FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid()
      AND role IN ('Admin', 'super_admin', 'Finance_Officer')
    )
  );

-- ── Step 11: Warehouse RLS — Warehouse_Staff for inventory ─────
DROP POLICY IF EXISTS "Warehouse staff can manage inventory" ON public.inventory;
CREATE POLICY "Warehouse staff can manage inventory"
  ON public.inventory FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid()
      AND role IN ('Admin', 'super_admin', 'Manager', 'Warehouse_Staff')
    )
  );

-- ── Done ───────────────────────────────────────────────────────
SELECT 'Migration 007_multi_portal.sql completed successfully' AS result;
