-- ============================================================
--  NEXUS TECHHUB — WMS (Warehouse Management System)
--  Migration: 008_warehouse_management.sql
-- ============================================================

-- ── 1. Role Helper Function ───────────────────────────────────
CREATE OR REPLACE FUNCTION public.is_inventory_officer()
RETURNS BOOLEAN AS $$
  SELECT public.get_my_role() IN ('Admin', 'super_admin', 'inventory', 'Manager');
$$ LANGUAGE sql STABLE SECURITY DEFINER;


-- ── 2. Warehouse Locations ────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.warehouse_locations (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(255) NOT NULL,
  location        TEXT,
  capacity        INT DEFAULT 0,
  current_stock   INT DEFAULT 0,
  manager_id      UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  status          VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'maintenance')),
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3. Goods Received (GRN) ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public.goods_received (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id      BIGINT REFERENCES public.suppliers(id) ON DELETE RESTRICT,
  reference_number VARCHAR(100),
  invoice_url      TEXT,
  delivery_note_url TEXT,
  received_by      UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  status           VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'partial')),
  notes            TEXT,
  received_date    TIMESTAMPTZ DEFAULT NOW(),
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ── 4. Stock Transfers ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.stock_transfers (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id        BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  from_warehouse_id BIGINT REFERENCES public.warehouse_locations(id) ON DELETE RESTRICT,
  to_warehouse_id   BIGINT REFERENCES public.warehouse_locations(id) ON DELETE RESTRICT,
  quantity          INT NOT NULL CHECK (quantity > 0),
  requested_by      UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  approved_by       UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  status            VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'in_transit', 'completed', 'cancelled')),
  notes             TEXT,
  transfer_date     TIMESTAMPTZ,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- ── 5. Damaged Stock ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.damaged_stock (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id      BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  quantity        INT NOT NULL CHECK (quantity > 0),
  reason          TEXT NOT NULL,
  photo_url       TEXT,
  reported_by     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  approved_by     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  status          VARCHAR(20) DEFAULT 'reported' CHECK (status IN ('reported', 'approved', 'disposed', 'rejected')),
  warehouse_id    BIGINT REFERENCES public.warehouse_locations(id) ON DELETE SET NULL,
  notes           TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── 6. Inventory Notifications ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.inventory_notifications (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type            VARCHAR(50) NOT NULL CHECK (type IN ('low_stock', 'po_approved', 'transfer', 'delivery_arrived', 'damage_reported')),
  title           VARCHAR(255) NOT NULL,
  message         TEXT NOT NULL,
  is_read         BOOLEAN DEFAULT FALSE,
  related_entity_id BIGINT,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── 7. Inventory Reports ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.inventory_reports (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(255) NOT NULL,
  type            VARCHAR(50) NOT NULL CHECK (type IN ('valuation', 'movement', 'low_stock', 'out_of_stock', 'damaged', 'grn')),
  generated_by    UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  file_url        TEXT NOT NULL,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================
--  Triggers
-- ============================================================
CREATE TRIGGER warehouse_locations_updated_at BEFORE UPDATE ON public.warehouse_locations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER goods_received_updated_at BEFORE UPDATE ON public.goods_received FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER stock_transfers_updated_at BEFORE UPDATE ON public.stock_transfers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER damaged_stock_updated_at BEFORE UPDATE ON public.damaged_stock FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
--  Enable RLS
-- ============================================================
ALTER TABLE public.warehouse_locations      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goods_received           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_transfers          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.damaged_stock            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_notifications  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_reports        ENABLE ROW LEVEL SECURITY;


-- ============================================================
--  RLS Policies (Inventory Role & Admin)
-- ============================================================

-- Warehouse Locations
CREATE POLICY "Inventory read warehouses" ON public.warehouse_locations FOR SELECT USING (public.is_inventory_officer());
CREATE POLICY "Inventory insert warehouses" ON public.warehouse_locations FOR INSERT WITH CHECK (public.is_inventory_officer());
CREATE POLICY "Inventory update warehouses" ON public.warehouse_locations FOR UPDATE USING (public.is_inventory_officer());

-- Goods Received
CREATE POLICY "Inventory read GRN" ON public.goods_received FOR SELECT USING (public.is_inventory_officer());
CREATE POLICY "Inventory insert GRN" ON public.goods_received FOR INSERT WITH CHECK (public.is_inventory_officer());
CREATE POLICY "Inventory update GRN" ON public.goods_received FOR UPDATE USING (public.is_inventory_officer());

-- Stock Transfers
CREATE POLICY "Inventory read transfers" ON public.stock_transfers FOR SELECT USING (public.is_inventory_officer());
CREATE POLICY "Inventory insert transfers" ON public.stock_transfers FOR INSERT WITH CHECK (public.is_inventory_officer());
CREATE POLICY "Inventory update transfers" ON public.stock_transfers FOR UPDATE USING (public.is_inventory_officer());

-- Damaged Stock
CREATE POLICY "Inventory read damaged" ON public.damaged_stock FOR SELECT USING (public.is_inventory_officer());
CREATE POLICY "Inventory insert damaged" ON public.damaged_stock FOR INSERT WITH CHECK (public.is_inventory_officer());
CREATE POLICY "Inventory update damaged" ON public.damaged_stock FOR UPDATE USING (public.is_inventory_officer());

-- Notifications & Reports
CREATE POLICY "Inventory read notifications" ON public.inventory_notifications FOR SELECT USING (public.is_inventory_officer());
CREATE POLICY "Inventory insert notifications" ON public.inventory_notifications FOR INSERT WITH CHECK (public.is_inventory_officer());
CREATE POLICY "Inventory update notifications" ON public.inventory_notifications FOR UPDATE USING (public.is_inventory_officer());

CREATE POLICY "Inventory read reports" ON public.inventory_reports FOR SELECT USING (public.is_inventory_officer());
CREATE POLICY "Inventory insert reports" ON public.inventory_reports FOR INSERT WITH CHECK (public.is_inventory_officer());


-- ============================================================
--  Grant Access to Existing Tables
-- ============================================================
-- Ensure the new `inventory` role is handled by existing functions (like `is_staff` if needed)
-- But we already mapped it explicitly in `is_inventory_officer`. Let's update `is_warehouse_staff`
-- to include the new 'inventory' role keyword since the old one was 'Warehouse_Staff'.

CREATE OR REPLACE FUNCTION public.is_warehouse_staff()
RETURNS BOOLEAN AS $$
  SELECT public.get_my_role() IN ('Admin', 'super_admin', 'Manager', 'Warehouse_Staff', 'inventory');
$$ LANGUAGE sql STABLE SECURITY DEFINER;


-- ============================================================
--  Enable Realtime on new tables
-- ============================================================
ALTER PUBLICATION supabase_realtime ADD TABLE public.goods_received;
ALTER PUBLICATION supabase_realtime ADD TABLE public.stock_transfers;
ALTER PUBLICATION supabase_realtime ADD TABLE public.inventory_notifications;
