-- ============================================================
--  NEXUS TECHHUB -- Phase 2 Inventory WMS Migration
--  Migration: 009_phase2_inventory.sql
-- ============================================================

-- 1. Extend profiles role to include inventory
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check
  CHECK (role IN ('Admin','super_admin','Manager','Customer','Warehouse_Staff','Finance_Officer','Dispatch_Officer','Driver','Supplier','inventory'));

-- 2. Extend transactions type constraint
ALTER TABLE public.transactions DROP CONSTRAINT IF EXISTS transactions_type_check;
ALTER TABLE public.transactions ADD CONSTRAINT transactions_type_check
  CHECK (type IN ('income','expense','Asset Increase','Asset Reduction','Write-off','Transfer'));

-- 3. Create purchase_requests table
CREATE TABLE IF NOT EXISTS public.purchase_requests (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id      BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  supplier_id     BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
  warehouse_id    BIGINT REFERENCES public.warehouse_locations(id) ON DELETE SET NULL,
  quantity        INT NOT NULL DEFAULT 1,
  unit_cost       DECIMAL(10,2) DEFAULT 70,
  total_cost      DECIMAL(12,2),
  status          VARCHAR(30) DEFAULT 'Pending'
                  CHECK (status IN ('Pending','Approved','Rejected','In Transit','Received','Cancelled','Awaiting Approval')),
  priority        VARCHAR(20) DEFAULT 'normal' CHECK (priority IN ('low','normal','high','urgent')),
  requested_by    UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  approved_by     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  notes           TEXT,
  expected_delivery DATE,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Add warehouse_id to inventory
ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS warehouse_id BIGINT REFERENCES public.warehouse_locations(id) ON DELETE SET NULL;

-- 5. Drop old unique constraint
ALTER TABLE public.inventory DROP CONSTRAINT IF EXISTS inventory_product_id_key;
CREATE UNIQUE INDEX IF NOT EXISTS idx_inventory_product_warehouse ON public.inventory(product_id, warehouse_id) WHERE warehouse_id IS NOT NULL;

-- 6. Create inventory_movements table
CREATE TABLE IF NOT EXISTS public.inventory_movements (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id    BIGINT REFERENCES public.inventory(id) ON DELETE CASCADE,
  movement_type   VARCHAR(30) NOT NULL CHECK (movement_type IN ('IN','OUT','ADJUSTMENT','TRANSFER_IN','TRANSFER_OUT','DAMAGE','DISPOSAL','RETURN','RECEIPT')),
  quantity        INT NOT NULL,
  quantity_before INT DEFAULT 0,
  quantity_after  INT DEFAULT 0,
  reason          TEXT,
  reference       VARCHAR(255),
  user_id         UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  related_id      BIGINT,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Add columns to warehouse_locations
ALTER TABLE public.warehouse_locations
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS current_utilization INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(50),
  ADD COLUMN IF NOT EXISTS is_default BOOLEAN DEFAULT FALSE;
UPDATE public.warehouse_locations SET address = location WHERE address IS NULL AND location IS NOT NULL;

-- 8. Add inventory_id to damaged_stock
ALTER TABLE public.damaged_stock ADD COLUMN IF NOT EXISTS inventory_id BIGINT REFERENCES public.inventory(id) ON DELETE CASCADE;
ALTER TABLE public.damaged_stock DROP CONSTRAINT IF EXISTS damaged_stock_status_check;
ALTER TABLE public.damaged_stock ADD CONSTRAINT damaged_stock_status_check
  CHECK (status IN ('reported','Reported','pending_approval','Pending Approval','approved','Approved','repair','Repair','return_to_supplier','Return to Supplier','disposed','Disposed','rejected','Rejected','written_off','Written Off'));
ALTER TABLE public.damaged_stock
  ADD COLUMN IF NOT EXISTS action_type VARCHAR(50),
  ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
  ADD COLUMN IF NOT EXISTS responsible_staff UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS image_urls TEXT[],
  ADD COLUMN IF NOT EXISTS reference_number VARCHAR(50);

-- 9. Add columns to stock_transfers
ALTER TABLE public.stock_transfers
  ADD COLUMN IF NOT EXISTS reference_number VARCHAR(50),
  ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
  ADD COLUMN IF NOT EXISTS received_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS received_date TIMESTAMPTZ;
ALTER TABLE public.stock_transfers DROP CONSTRAINT IF EXISTS stock_transfers_status_check;
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_status_check
  CHECK (status IN ('pending','approved','rejected','in_transit','received','completed','cancelled'));

-- 10. Create stock_alerts table
CREATE TABLE IF NOT EXISTS public.stock_alerts (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_type       VARCHAR(50) NOT NULL,
  severity         VARCHAR(20) DEFAULT 'warning' CHECK (severity IN ('info','warning','critical','urgent')),
  priority         INT DEFAULT 5,
  title            VARCHAR(255) NOT NULL,
  message          TEXT NOT NULL,
  suggested_action TEXT,
  product_id       BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  warehouse_id     BIGINT REFERENCES public.warehouse_locations(id) ON DELETE SET NULL,
  inventory_id     BIGINT REFERENCES public.inventory(id) ON DELETE CASCADE,
  sku              VARCHAR(100),
  status           VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active','acknowledged','resolved')),
  is_read          BOOLEAN DEFAULT FALSE,
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Enable RLS
ALTER TABLE public.purchase_requests   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_alerts        ENABLE ROW LEVEL SECURITY;

-- 12. Update helper functions
CREATE OR REPLACE FUNCTION public.is_inventory_officer()
RETURNS BOOLEAN AS $$
  SELECT public.get_my_role() IN ('Admin','super_admin','Manager','Warehouse_Staff','inventory');
$$ LANGUAGE sql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_warehouse_staff()
RETURNS BOOLEAN AS $$
  SELECT public.get_my_role() IN ('Admin','super_admin','Manager','Warehouse_Staff','inventory');
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- 13. RLS for purchase_requests
DROP POLICY IF EXISTS "Inventory read purchase_requests"   ON public.purchase_requests;
DROP POLICY IF EXISTS "Inventory insert purchase_requests" ON public.purchase_requests;
DROP POLICY IF EXISTS "Inventory update purchase_requests" ON public.purchase_requests;
DROP POLICY IF EXISTS "Inventory delete purchase_requests" ON public.purchase_requests;
CREATE POLICY "Inventory read purchase_requests"   ON public.purchase_requests FOR SELECT USING (public.is_inventory_officer());
CREATE POLICY "Inventory insert purchase_requests" ON public.purchase_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Inventory update purchase_requests" ON public.purchase_requests FOR UPDATE USING (public.is_inventory_officer());
CREATE POLICY "Inventory delete purchase_requests" ON public.purchase_requests FOR DELETE USING (public.is_inventory_officer());

-- 14. RLS for inventory_movements
DROP POLICY IF EXISTS "Inventory read movements"   ON public.inventory_movements;
DROP POLICY IF EXISTS "Inventory insert movements" ON public.inventory_movements;
CREATE POLICY "Inventory read movements"   ON public.inventory_movements FOR SELECT USING (public.is_inventory_officer());
CREATE POLICY "Inventory insert movements" ON public.inventory_movements FOR INSERT WITH CHECK (true);

-- 15. RLS for stock_alerts
DROP POLICY IF EXISTS "Inventory read alerts"   ON public.stock_alerts;
DROP POLICY IF EXISTS "Inventory insert alerts" ON public.stock_alerts;
DROP POLICY IF EXISTS "Inventory update alerts" ON public.stock_alerts;
CREATE POLICY "Inventory read alerts"   ON public.stock_alerts FOR SELECT USING (public.is_inventory_officer());
CREATE POLICY "Inventory insert alerts" ON public.stock_alerts FOR INSERT WITH CHECK (true);
CREATE POLICY "Inventory update alerts" ON public.stock_alerts FOR UPDATE USING (public.is_inventory_officer());

DROP POLICY IF EXISTS "Inventory delete damaged" ON public.damaged_stock;
CREATE POLICY "Inventory delete damaged" ON public.damaged_stock FOR DELETE USING (public.is_inventory_officer());

-- 16. Updated_at triggers
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'purchase_requests_updated_at') THEN
    CREATE TRIGGER purchase_requests_updated_at BEFORE UPDATE ON public.purchase_requests FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'stock_alerts_updated_at') THEN
    CREATE TRIGGER stock_alerts_updated_at BEFORE UPDATE ON public.stock_alerts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

-- 17. Performance indexes
CREATE INDEX IF NOT EXISTS idx_inventory_product       ON public.inventory(product_id);
CREATE INDEX IF NOT EXISTS idx_inventory_warehouse     ON public.inventory(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_inv_movements_inventory ON public.inventory_movements(inventory_id);
CREATE INDEX IF NOT EXISTS idx_inv_movements_type      ON public.inventory_movements(movement_type);
CREATE INDEX IF NOT EXISTS idx_inv_movements_created   ON public.inventory_movements(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pr_status               ON public.purchase_requests(status);
CREATE INDEX IF NOT EXISTS idx_pr_product              ON public.purchase_requests(product_id);
CREATE INDEX IF NOT EXISTS idx_damaged_inventory       ON public.damaged_stock(inventory_id);
CREATE INDEX IF NOT EXISTS idx_alerts_status           ON public.stock_alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_type             ON public.stock_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_transfers_status        ON public.stock_transfers(status);
CREATE INDEX IF NOT EXISTS idx_transfers_product       ON public.stock_transfers(product_id);

-- 18. RPC: receive_goods
CREATE OR REPLACE FUNCTION public.receive_goods(
  p_request_id   BIGINT,
  p_warehouse_id BIGINT,
  p_quantity     INT,
  p_user_id      UUID
) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_product_id   BIGINT;
  v_supplier_id  BIGINT;
  v_unit_cost    DECIMAL(10,2);
  v_inventory_id BIGINT;
  v_qty_before   INT := 0;
  v_qty_after    INT;
BEGIN
  SELECT product_id, supplier_id, COALESCE(unit_cost, 70)
  INTO v_product_id, v_supplier_id, v_unit_cost
  FROM public.purchase_requests WHERE id = p_request_id;

  IF v_product_id IS NULL THEN
    RAISE EXCEPTION 'Purchase request % not found', p_request_id;
  END IF;

  SELECT id, quantity_on_hand INTO v_inventory_id, v_qty_before
  FROM public.inventory
  WHERE product_id = v_product_id AND warehouse_id = p_warehouse_id LIMIT 1;

  IF v_inventory_id IS NULL THEN
    SELECT id, quantity_on_hand INTO v_inventory_id, v_qty_before
    FROM public.inventory WHERE product_id = v_product_id LIMIT 1;
  END IF;

  IF v_inventory_id IS NULL THEN
    INSERT INTO public.inventory (product_id, warehouse_id, quantity_on_hand, supplier_id, cost_price)
    VALUES (v_product_id, p_warehouse_id, 0, v_supplier_id, v_unit_cost)
    RETURNING id INTO v_inventory_id;
    v_qty_before := 0;
  ELSE
    UPDATE public.inventory SET warehouse_id = COALESCE(warehouse_id, p_warehouse_id) WHERE id = v_inventory_id;
  END IF;

  v_qty_after := COALESCE(v_qty_before, 0) + p_quantity;

  UPDATE public.inventory SET quantity_on_hand = v_qty_after, last_restocked = NOW(), updated_at = NOW() WHERE id = v_inventory_id;
  UPDATE public.products SET stock = v_qty_after WHERE id = v_product_id;
  UPDATE public.purchase_requests SET status = 'Received', approved_by = p_user_id, updated_at = NOW() WHERE id = p_request_id;

  INSERT INTO public.inventory_movements (inventory_id, movement_type, quantity, quantity_before, quantity_after, reason, user_id, reference)
  VALUES (v_inventory_id, 'IN', p_quantity, COALESCE(v_qty_before, 0), v_qty_after, 'Goods Received via PR #' || p_request_id::text, p_user_id, 'PR-' || p_request_id::text);

  INSERT INTO public.transactions (type, category, description, amount, user_id, supplier_id, status, transaction_date)
  VALUES ('Asset Increase', 'Inventory', 'Stock received via PR #' || p_request_id::text, p_quantity * v_unit_cost, p_user_id, v_supplier_id, 'completed', CURRENT_DATE);
END;
$$;

-- 19. RPC: dispose_damaged_stock
CREATE OR REPLACE FUNCTION public.dispose_damaged_stock(
  p_damage_id BIGINT,
  p_user_id   UUID
) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_inventory_id BIGINT;
  v_product_id   BIGINT;
  v_quantity     INT;
  v_cost_price   DECIMAL(10,2);
  v_qty_before   INT := 0;
  v_qty_after    INT;
BEGIN
  SELECT COALESCE(ds.inventory_id, (SELECT inv.id FROM public.inventory inv WHERE inv.product_id = ds.product_id LIMIT 1)), ds.quantity
  INTO v_inventory_id, v_quantity
  FROM public.damaged_stock ds WHERE ds.id = p_damage_id;

  IF v_inventory_id IS NULL THEN
    RAISE EXCEPTION 'Damaged stock % has no linked inventory', p_damage_id;
  END IF;

  SELECT quantity_on_hand, cost_price, product_id INTO v_qty_before, v_cost_price, v_product_id
  FROM public.inventory WHERE id = v_inventory_id;

  v_qty_after := GREATEST(0, COALESCE(v_qty_before, 0) - v_quantity);

  UPDATE public.inventory SET quantity_on_hand = v_qty_after, updated_at = NOW() WHERE id = v_inventory_id;
  UPDATE public.products SET stock = v_qty_after WHERE id = v_product_id;
  UPDATE public.damaged_stock SET status = 'disposed', approved_by = p_user_id, updated_at = NOW() WHERE id = p_damage_id;

  INSERT INTO public.inventory_movements (inventory_id, movement_type, quantity, quantity_before, quantity_after, reason, user_id)
  VALUES (v_inventory_id, 'DAMAGE', -v_quantity, COALESCE(v_qty_before, 0), v_qty_after, 'Damaged stock disposed ID #' || p_damage_id::text, p_user_id);

  INSERT INTO public.transactions (type, category, description, amount, user_id, status, transaction_date)
  VALUES ('Write-off', 'Inventory Loss', 'Damaged stock write-off ID #' || p_damage_id::text, v_quantity * COALESCE(v_cost_price, 0), p_user_id, 'completed', CURRENT_DATE);
END;
$$;

-- 20. RPC: transfer_stock
CREATE OR REPLACE FUNCTION public.transfer_stock(
  p_product_id          BIGINT,
  p_source_warehouse_id BIGINT,
  p_dest_warehouse_id   BIGINT,
  p_quantity            INT,
  p_user_id             UUID
) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_src_inv_id  BIGINT;
  v_dst_inv_id  BIGINT;
  v_src_qty     INT;
  v_dst_qty     INT := 0;
  v_cost_price  DECIMAL(10,2);
  v_supplier_id BIGINT;
  v_ref_num     VARCHAR(50);
BEGIN
  SELECT id, quantity_on_hand, cost_price, supplier_id INTO v_src_inv_id, v_src_qty, v_cost_price, v_supplier_id
  FROM public.inventory
  WHERE product_id = p_product_id AND (warehouse_id = p_source_warehouse_id OR warehouse_id IS NULL)
  ORDER BY (warehouse_id = p_source_warehouse_id) DESC NULLS LAST LIMIT 1;

  IF v_src_inv_id IS NULL THEN
    RAISE EXCEPTION 'No inventory found for product % in source warehouse %', p_product_id, p_source_warehouse_id;
  END IF;
  IF COALESCE(v_src_qty, 0) < p_quantity THEN
    RAISE EXCEPTION 'Insufficient stock. Available: %, Requested: %', COALESCE(v_src_qty, 0), p_quantity;
  END IF;

  UPDATE public.inventory SET quantity_on_hand = quantity_on_hand - p_quantity, updated_at = NOW() WHERE id = v_src_inv_id;

  SELECT id, quantity_on_hand INTO v_dst_inv_id, v_dst_qty
  FROM public.inventory WHERE product_id = p_product_id AND warehouse_id = p_dest_warehouse_id LIMIT 1;

  IF v_dst_inv_id IS NULL THEN
    INSERT INTO public.inventory (product_id, warehouse_id, quantity_on_hand, cost_price, supplier_id)
    VALUES (p_product_id, p_dest_warehouse_id, 0, v_cost_price, v_supplier_id) RETURNING id INTO v_dst_inv_id;
    v_dst_qty := 0;
  END IF;

  UPDATE public.inventory SET quantity_on_hand = quantity_on_hand + p_quantity, updated_at = NOW() WHERE id = v_dst_inv_id;

  v_ref_num := 'TRF-' || TO_CHAR(NOW(), 'YYYYMMDD') || '-' || LPAD(FLOOR(RANDOM() * 9999)::TEXT, 4, '0');

  INSERT INTO public.inventory_movements (inventory_id, movement_type, quantity, quantity_before, quantity_after, reason, user_id, reference)
  VALUES
    (v_src_inv_id, 'TRANSFER_OUT', -p_quantity, COALESCE(v_src_qty, 0), COALESCE(v_src_qty, 0) - p_quantity, 'Transfer to WH ' || p_dest_warehouse_id::text, p_user_id, v_ref_num),
    (v_dst_inv_id, 'TRANSFER_IN',  p_quantity,  COALESCE(v_dst_qty, 0), COALESCE(v_dst_qty, 0) + p_quantity,  'Transfer from WH ' || p_source_warehouse_id::text, p_user_id, v_ref_num);

  UPDATE public.products SET stock = (SELECT COALESCE(SUM(quantity_on_hand), 0) FROM public.inventory WHERE product_id = p_product_id) WHERE id = p_product_id;

  INSERT INTO public.stock_transfers (product_id, from_warehouse_id, to_warehouse_id, quantity, requested_by, approved_by, status, transfer_date)
  VALUES (p_product_id, p_source_warehouse_id, p_dest_warehouse_id, p_quantity, p_user_id, p_user_id, 'completed', NOW());
END;
$$;

-- 21. generate_stock_alert helper
CREATE OR REPLACE FUNCTION public.generate_stock_alert(p_inventory_id BIGINT, p_alert_type VARCHAR, p_severity VARCHAR DEFAULT 'warning')
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_title TEXT; v_msg TEXT; v_action TEXT;
  v_product_title VARCHAR; v_sku VARCHAR;
  v_product_id BIGINT; v_warehouse_id BIGINT; v_qty INT; v_reorder INT;
BEGIN
  SELECT p.title, p.sku, i.product_id, i.warehouse_id, i.quantity_on_hand, i.reorder_level
  INTO v_product_title, v_sku, v_product_id, v_warehouse_id, v_qty, v_reorder
  FROM public.inventory i JOIN public.products p ON p.id = i.product_id WHERE i.id = p_inventory_id;

  CASE p_alert_type
    WHEN 'out_of_stock' THEN v_title := 'Out of Stock: ' || COALESCE(v_product_title,'?'); v_msg := COALESCE(v_product_title,'Product') || ' is out of stock.'; v_action := 'Create a purchase request immediately.';
    WHEN 'low_stock'    THEN v_title := 'Low Stock: '    || COALESCE(v_product_title,'?'); v_msg := COALESCE(v_product_title,'Product') || ' has only ' || COALESCE(v_qty::text,'0') || ' units.'; v_action := 'Replenish stock soon.';
    WHEN 'overstock'    THEN v_title := 'Overstock: '    || COALESCE(v_product_title,'?'); v_msg := COALESCE(v_product_title,'Product') || ' exceeds max threshold (' || COALESCE(v_qty::text,'0') || ' units).'; v_action := 'Consider promotions or transfers.';
    ELSE v_title := 'Alert: ' || COALESCE(v_product_title,'?'); v_msg := 'Inventory issue detected.'; v_action := 'Review inventory.';
  END CASE;

  INSERT INTO public.stock_alerts (alert_type, severity, title, message, suggested_action, product_id, warehouse_id, inventory_id, sku, status)
  SELECT p_alert_type, p_severity, v_title, v_msg, v_action, v_product_id, v_warehouse_id, p_inventory_id, v_sku, 'active'
  WHERE NOT EXISTS (SELECT 1 FROM public.stock_alerts WHERE inventory_id = p_inventory_id AND alert_type = p_alert_type AND status = 'active' AND created_at > NOW() - INTERVAL '24 hours');
END;
$$;

-- 22. Auto-health trigger
CREATE OR REPLACE FUNCTION public.evaluate_inventory_health() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.quantity_on_hand <= 0 THEN
    PERFORM public.generate_stock_alert(NEW.id, 'out_of_stock', 'critical');
  ELSIF NEW.quantity_on_hand <= COALESCE(NEW.reorder_level, 10) THEN
    PERFORM public.generate_stock_alert(NEW.id, 'low_stock', 'warning');
  ELSIF NEW.quantity_on_hand > COALESCE(NEW.reorder_level, 10) * 5 THEN
    PERFORM public.generate_stock_alert(NEW.id, 'overstock', 'info');
  ELSE
    UPDATE public.stock_alerts SET status = 'resolved', updated_at = NOW()
    WHERE inventory_id = NEW.id AND alert_type IN ('out_of_stock','low_stock','overstock') AND status = 'active';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_evaluate_inventory_health ON public.inventory;
CREATE TRIGGER trigger_evaluate_inventory_health
  AFTER INSERT OR UPDATE OF quantity_on_hand ON public.inventory
  FOR EACH ROW EXECUTE FUNCTION public.evaluate_inventory_health();

-- 23. Realtime subscriptions
DO $$ BEGIN
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.purchase_requests;   EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.inventory_movements; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.stock_alerts;        EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.damaged_stock;       EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.stock_transfers;     EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

SELECT '009_phase2_inventory.sql completed' AS result;
