-- Finance ERP rebuild: retain shared data and reset only finance transactions.
-- This migration deliberately does not touch auth.users, profiles, orders, products,
-- inventory, suppliers, dispatch, or any admin-owned records.

CREATE TABLE IF NOT EXISTS public.finance_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number TEXT NOT NULL UNIQUE,
  customer_id UUID REFERENCES public.profiles(id) ON DELETE RESTRICT,
  customer_name TEXT NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
  status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Draft', 'Pending', 'Partially Paid', 'Paid', 'Cancelled')),
  due_date DATE,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.customer_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id UUID REFERENCES public.profiles(id) ON DELETE RESTRICT,
  customer_name TEXT NOT NULL,
  invoice_id BIGINT NOT NULL REFERENCES public.finance_invoices(id) ON DELETE RESTRICT,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  payment_method TEXT NOT NULL,
  reference_number TEXT NOT NULL UNIQUE,
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.finance_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Reset only finance transactional records; schema and the Finance Manager account remain.
DELETE FROM public.customer_payments;
DELETE FROM public.finance_invoices;
DELETE FROM public.finance_expenses;
DELETE FROM public.transactions;

CREATE OR REPLACE FUNCTION public.refresh_finance_invoice_status()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE target_invoice BIGINT := COALESCE(NEW.invoice_id, OLD.invoice_id);
BEGIN
  UPDATE public.finance_invoices invoice
  SET paid_amount = COALESCE((SELECT SUM(amount) FROM public.customer_payments WHERE invoice_id = target_invoice), 0),
      status = CASE
        WHEN invoice.status = 'Cancelled' THEN 'Cancelled'
        WHEN COALESCE((SELECT SUM(amount) FROM public.customer_payments WHERE invoice_id = target_invoice), 0) >= invoice.amount THEN 'Paid'
        WHEN COALESCE((SELECT SUM(amount) FROM public.customer_payments WHERE invoice_id = target_invoice), 0) > 0 THEN 'Partially Paid'
        ELSE 'Pending'
      END,
      updated_at = NOW()
  WHERE id = target_invoice;
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS finance_payment_updates_invoice ON public.customer_payments;
CREATE TRIGGER finance_payment_updates_invoice
AFTER INSERT OR UPDATE OR DELETE ON public.customer_payments
FOR EACH ROW EXECUTE FUNCTION public.refresh_finance_invoice_status();

CREATE OR REPLACE FUNCTION public.is_finance_user()
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid()
      AND role IN ('Admin', 'super_admin', 'Manager', 'Finance Manager', 'Finance Director', 'Accountant', 'Auditor', 'Finance_Officer')
  );
$$;

ALTER TABLE public.finance_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finance_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Finance ERP invoices" ON public.finance_invoices;
CREATE POLICY "Finance ERP invoices" ON public.finance_invoices FOR ALL USING (public.is_finance_user()) WITH CHECK (public.is_finance_user());
DROP POLICY IF EXISTS "Finance ERP payments" ON public.customer_payments;
CREATE POLICY "Finance ERP payments" ON public.customer_payments FOR ALL USING (public.is_finance_user()) WITH CHECK (public.is_finance_user());
DROP POLICY IF EXISTS "Finance ERP expenses" ON public.finance_expenses;
CREATE POLICY "Finance ERP expenses" ON public.finance_expenses FOR ALL USING (public.is_finance_user()) WITH CHECK (public.is_finance_user());
DROP POLICY IF EXISTS "Finance ERP transactions" ON public.transactions;
CREATE POLICY "Finance ERP transactions" ON public.transactions FOR ALL USING (public.is_finance_user()) WITH CHECK (public.is_finance_user());

CREATE INDEX IF NOT EXISTS finance_invoices_status_idx ON public.finance_invoices(status, created_at DESC);
CREATE INDEX IF NOT EXISTS customer_payments_invoice_idx ON public.customer_payments(invoice_id, payment_date DESC);
