-- Follow-up for environments where 012 was already applied.
-- Keeps the legacy public.expenses table untouched and creates the rebuilt Finance ERP table.
CREATE TABLE IF NOT EXISTS public.finance_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE public.finance_expenses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Finance ERP expenses" ON public.finance_expenses;
CREATE POLICY "Finance ERP expenses" ON public.finance_expenses FOR ALL USING (public.is_finance_user()) WITH CHECK (public.is_finance_user());
CREATE INDEX IF NOT EXISTS finance_expenses_date_idx ON public.finance_expenses(expense_date DESC);
