-- ============================================================
--  NEXUS TECHHUB — ERP Business Modules Migration
--  Migration: 016_supplier_portal.sql
-- ============================================================

-- 1. Extend the role CHECK constraint to include 'Supplier'
ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_role_check;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_role_check
  CHECK (role IN (
    'Admin',
    'super_admin',
    'Super_Admin',
    'Manager',
    'Customer',
    'Warehouse_Staff',
    'Dispatch_Officer',
    'Driver',
    'Supplier',
    'Inventory_Manager',
    'Finance_Manager'
  ));

-- 2. Add supplier_id to products
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS supplier_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;

-- 3. Add supplier_id to orders
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS supplier_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;

-- 4. Supplier Messages
CREATE TABLE IF NOT EXISTS public.supplier_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  department VARCHAR(50) NOT NULL,
  subject VARCHAR(255),
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  sender_role VARCHAR(50),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Supplier Notifications
CREATE TABLE IF NOT EXISTS public.supplier_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  type VARCHAR(50) DEFAULT 'info', -- 'info', 'warning', 'critical'
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Supplier Reports
CREATE TABLE IF NOT EXISTS public.supplier_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  report_name VARCHAR(255) NOT NULL,
  report_type VARCHAR(100),
  file_url VARCHAR(500),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Supplier Profiles (Extends existing profile with business details)
CREATE TABLE IF NOT EXISTS public.supplier_profiles (
  id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  business_name VARCHAR(255) NOT NULL,
  owner_name VARCHAR(255),
  phone VARCHAR(50),
  email VARCHAR(255),
  address TEXT,
  kra_pin VARCHAR(100),
  bank_details TEXT,
  business_logo VARCHAR(500),
  business_certificate VARCHAR(500),
  store_rating DECIMAL(3,2) DEFAULT 5.00,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Row Level Security

-- Enable RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_profiles ENABLE ROW LEVEL SECURITY;

-- Products RLS: Suppliers can CRUD their own products; others can read all active products
DROP POLICY IF EXISTS "Suppliers can manage their own products" ON public.products;
CREATE POLICY "Suppliers can manage their own products"
ON public.products
FOR ALL
USING (supplier_id = auth.uid() OR auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Super_Admin', 'super_admin')))
WITH CHECK (supplier_id = auth.uid() OR auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Super_Admin', 'super_admin')));

DROP POLICY IF EXISTS "Public can read active products" ON public.products;
CREATE POLICY "Public can read active products"
ON public.products
FOR SELECT
USING (true); -- Usually you'd check availability, but keeping it simple as before

-- Orders RLS: Suppliers can read/update their own orders; Customers can read their own
DROP POLICY IF EXISTS "Suppliers can read and update their own orders" ON public.orders;
CREATE POLICY "Suppliers can read and update their own orders"
ON public.orders
FOR ALL
USING (supplier_id = auth.uid() OR user_id = auth.uid() OR auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Super_Admin', 'super_admin')))
WITH CHECK (supplier_id = auth.uid() OR user_id = auth.uid() OR auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Super_Admin', 'super_admin')));

-- Supplier Messages RLS
DROP POLICY IF EXISTS "Suppliers manage their own messages" ON public.supplier_messages;
CREATE POLICY "Suppliers manage their own messages"
ON public.supplier_messages
FOR ALL
USING (supplier_id = auth.uid() OR auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Super_Admin', 'super_admin')))
WITH CHECK (supplier_id = auth.uid() OR auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Super_Admin', 'super_admin')));

-- Supplier Notifications RLS
DROP POLICY IF EXISTS "Suppliers manage their own notifications" ON public.supplier_notifications;
CREATE POLICY "Suppliers manage their own notifications"
ON public.supplier_notifications
FOR ALL
USING (supplier_id = auth.uid() OR auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Super_Admin', 'super_admin')))
WITH CHECK (supplier_id = auth.uid() OR auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Super_Admin', 'super_admin')));

-- Supplier Reports RLS
DROP POLICY IF EXISTS "Suppliers manage their own reports" ON public.supplier_reports;
CREATE POLICY "Suppliers manage their own reports"
ON public.supplier_reports
FOR ALL
USING (supplier_id = auth.uid() OR auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Super_Admin', 'super_admin')))
WITH CHECK (supplier_id = auth.uid() OR auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Super_Admin', 'super_admin')));

-- Supplier Profiles RLS
DROP POLICY IF EXISTS "Suppliers manage their own profiles" ON public.supplier_profiles;
CREATE POLICY "Suppliers manage their own profiles"
ON public.supplier_profiles
FOR ALL
USING (id = auth.uid() OR auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Super_Admin', 'super_admin')))
WITH CHECK (id = auth.uid() OR auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Super_Admin', 'super_admin')));
