-- ============================================================
-- MIGRATION 018: Full Order Workflow
-- Adds missing statuses, audit trail, order numbering,
-- inventory reservation, and dispatch auto-creation
-- ============================================================

-- 1. Drop old constraint first so we can freely update statuses
ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_status_check;

-- 2. Normalize all existing order statuses
UPDATE public.orders SET status = INITCAP(TRIM(status));

UPDATE public.orders SET status = 'Picking' WHERE status = 'Processing';
UPDATE public.orders SET status = 'Out for Delivery' WHERE status = 'Shipped';

-- Catch any remaining invalid statuses and default them to 'Pending'
UPDATE public.orders SET status = 'Pending'
  WHERE status NOT IN (
    'Pending', 'Awaiting Payment', 'Paid', 'Waiting for Stock', 'Reserved',
    'Picking', 'Packing', 'Ready for Dispatch', 'Assigned', 'Out for Delivery',
    'Delivered', 'Completed', 'Cancelled', 'Refunded', 'Pending Payment Verification',
    'Payment Failed'
  );

ALTER TABLE public.orders ADD CONSTRAINT orders_status_check
  CHECK (status IN (
    'Pending',
    'Awaiting Payment',
    'Paid',
    'Waiting for Stock',
    'Reserved',
    'Picking',
    'Packing',
    'Ready for Dispatch',
    'Assigned',
    'Out for Delivery',
    'Delivered',
    'Completed',
    'Cancelled',
    'Refunded',
    'Pending Payment Verification',
    'Payment Failed'
  ));

-- 2. Add payment_method column if not exists
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS order_number VARCHAR(20);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS priority VARCHAR(10) DEFAULT 'normal'
  CHECK (priority IN ('low', 'normal', 'high', 'urgent'));
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS warehouse_id UUID REFERENCES public.warehouse_locations(id);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS driver_id UUID REFERENCES public.profiles(id);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS picked_at TIMESTAMPTZ;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS packed_at TIMESTAMPTZ;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS dispatched_at TIMESTAMPTZ;

-- 3. Create order_status_history table
CREATE TABLE IF NOT EXISTS public.order_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  from_status VARCHAR(50),
  to_status VARCHAR(50) NOT NULL,
  changed_by UUID REFERENCES public.profiles(id),
  changed_at TIMESTAMPTZ DEFAULT NOW(),
  note TEXT,
  metadata JSONB
);

CREATE INDEX IF NOT EXISTS idx_order_status_history_order_id ON public.order_status_history(order_id);
CREATE INDEX IF NOT EXISTS idx_order_status_history_changed_at ON public.order_status_history(changed_at DESC);

ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'order_status_history' AND policyname = 'Admins can manage order_status_history'
  ) THEN
    CREATE POLICY "Admins can manage order_status_history" ON public.order_status_history
      FOR ALL USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'super_admin', 'Manager'))
      );
  END IF;
END $$;

-- 4. Auto-generate order_number on insert
CREATE OR REPLACE FUNCTION public.generate_order_number()
RETURNS TRIGGER AS $$
DECLARE
  seq_num INT;
  date_part VARCHAR(8);
BEGIN
  date_part := TO_CHAR(NOW(), 'YYYYMMDD');
  seq_num := nextval('orders_seq')::INT % 10000;
  NEW.order_number := 'ORD-' || date_part || '-' || LPAD(seq_num::TEXT, 4, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'orders_seq') THEN
    CREATE SEQUENCE public.orders_seq START 1001;
  END IF;
END $$;

DROP TRIGGER IF EXISTS trg_generate_order_number ON public.orders;
CREATE TRIGGER trg_generate_order_number
  BEFORE INSERT ON public.orders
  FOR EACH ROW
  WHEN (NEW.order_number IS NULL)
  EXECUTE FUNCTION public.generate_order_number();

-- 5. Auto-log status changes
CREATE OR REPLACE FUNCTION public.log_order_status_change()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.status IS DISTINCT FROM NEW.status THEN
    INSERT INTO public.order_status_history (order_id, from_status, to_status, changed_by, changed_at)
    VALUES (NEW.id, OLD.status, NEW.status, auth.uid(), NOW());
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_log_order_status ON public.orders;
CREATE TRIGGER trg_log_order_status
  AFTER UPDATE OF status ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.log_order_status_change();

-- 6. Add supplier_id to orders if not present
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS supplier_id UUID REFERENCES public.suppliers(id);

-- 7. Create picking_lists table
CREATE TABLE IF NOT EXISTS public.picking_lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  warehouse_id UUID REFERENCES public.warehouse_locations(id),
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled')),
  assigned_to UUID REFERENCES public.profiles(id),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.picking_list_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  picking_list_id BIGINT NOT NULL REFERENCES public.picking_lists(id) ON DELETE CASCADE,
  product_id UUID REFERENCES public.products(id),
  quantity_expected INT NOT NULL,
  quantity_picked INT DEFAULT 0,
  location_code VARCHAR(50),
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'picked', 'skipped'))
);

-- 8. Create packing_lists table
CREATE TABLE IF NOT EXISTS public.packing_lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  picking_list_id BIGINT REFERENCES public.picking_lists(id),
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled')),
  packed_by UUID REFERENCES public.profiles(id),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  package_weight DECIMAL(10,2),
  package_dimensions VARCHAR(50),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.picking_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.picking_list_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.packing_lists ENABLE ROW LEVEL SECURITY;

-- 9. Create/Replace reserve_inventory RPC
CREATE OR REPLACE FUNCTION public.reserve_inventory(p_order_id UUID, p_user_id UUID)
RETURNS JSONB AS $$
DECLARE
  v_item RECORD;
  v_inventory RECORD;
  v_available INT;
  v_all_available BOOLEAN := TRUE;
  v_low_stock_items JSONB := '[]'::JSONB;
  v_result JSONB;
BEGIN
  FOR v_item IN
    SELECT oi.product_id, oi.quantity, p.title
    FROM public.order_items oi
    JOIN public.products p ON p.id = oi.product_id
    WHERE oi.order_id = p_order_id
  LOOP
    SELECT i.id, i.quantity_on_hand, i.quantity_reserved, i.reorder_level
    INTO v_inventory
    FROM public.inventory i
    WHERE i.product_id = v_item.product_id
    LIMIT 1;

    IF v_inventory.id IS NULL THEN
      INSERT INTO public.inventory (product_id, quantity_on_hand, quantity_reserved)
      VALUES (v_item.product_id, 0, 0)
      RETURNING id, quantity_on_hand, quantity_reserved, reorder_level INTO v_inventory;
    END IF;

    v_available := COALESCE(v_inventory.quantity_on_hand, 0) - COALESCE(v_inventory.quantity_reserved, 0);

    IF v_available >= v_item.quantity THEN
      UPDATE public.inventory
      SET quantity_reserved = COALESCE(quantity_reserved, 0) + v_item.quantity,
          updated_at = NOW()
      WHERE id = v_inventory.id;
    ELSE
      v_all_available := FALSE;
      v_low_stock_items := v_low_stock_items || jsonb_build_object(
        'product_id', v_item.product_id,
        'title', v_item.title,
        'requested', v_item.quantity,
        'available', GREATEST(0, v_available)
      );
    END IF;
  END LOOP;

  IF v_all_available THEN
    UPDATE public.orders SET status = 'Reserved' WHERE id = p_order_id;
    v_result := jsonb_build_object('success', TRUE, 'status', 'Reserved');
  ELSE
    UPDATE public.orders SET status = 'Waiting for Stock' WHERE id = p_order_id;
    v_result := jsonb_build_object(
      'success', FALSE,
      'status', 'Waiting for Stock',
      'low_stock_items', v_low_stock_items
    );
  END IF;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 10. Create/Replace release_inventory RPC
CREATE OR REPLACE FUNCTION public.release_inventory(p_order_id UUID)
RETURNS JSONB AS $$
DECLARE
  v_item RECORD;
BEGIN
  FOR v_item IN
    SELECT oi.product_id, oi.quantity
    FROM public.order_items oi
    WHERE oi.order_id = p_order_id
  LOOP
    UPDATE public.inventory
    SET quantity_reserved = GREATEST(0, COALESCE(quantity_reserved, 0) - v_item.quantity),
        updated_at = NOW()
    WHERE product_id = v_item.product_id;
  END LOOP;

  RETURN jsonb_build_object('success', TRUE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 11. Create/Replace deduct_inventory RPC (called when picking completed)
CREATE OR REPLACE FUNCTION public.deduct_inventory(p_order_id UUID)
RETURNS JSONB AS $$
DECLARE
  v_item RECORD;
BEGIN
  FOR v_item IN
    SELECT oi.product_id, oi.quantity
    FROM public.order_items oi
    WHERE oi.order_id = p_order_id
  LOOP
    UPDATE public.inventory
    SET quantity_on_hand = GREATEST(0, COALESCE(quantity_on_hand, 0) - v_item.quantity),
        quantity_reserved = GREATEST(0, COALESCE(quantity_reserved, 0) - v_item.quantity),
        updated_at = NOW()
    WHERE product_id = v_item.product_id;

    UPDATE public.products
    SET stock = GREATEST(0, COALESCE(stock, 0) - v_item.quantity)
    WHERE id = v_item.product_id;

    INSERT INTO public.inventory_logs (product_id, order_id, change_amount, reason, notes)
    VALUES (v_item.product_id, p_order_id, -v_item.quantity, 'sale', 'Picking completed');
  END LOOP;

  RETURN jsonb_build_object('success', TRUE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 12. Create auto_create_dispatch function unconditionally (no table refs checked at compile time)
CREATE OR REPLACE FUNCTION public.auto_create_dispatch()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER AS $func$
DECLARE
  v_has_dispatches BOOLEAN;
  v_has_notifications BOOLEAN;
BEGIN
  IF NEW.status = 'Ready for Dispatch' AND (OLD.status IS DISTINCT FROM 'Ready for Dispatch') THEN
    SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'dispatches') INTO v_has_dispatches;
    SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'portal_notifications') INTO v_has_notifications;

    IF v_has_dispatches THEN
      INSERT INTO public.dispatches (order_id, customer_name, customer_phone, delivery_address, delivery_city, status, created_at)
      SELECT NEW.id, COALESCE(NEW.shipping_name, p.full_name), NEW.shipping_phone, NEW.shipping_address, NEW.shipping_city, 'pending', NOW()
      FROM public.profiles p WHERE p.id = NEW.user_id;
    END IF;

    IF v_has_notifications THEN
      INSERT INTO public.portal_notifications (user_id, type, title, message, portal)
      SELECT user_id, 'dispatch', 'Dispatch Created',
        'Order ' || COALESCE(NEW.order_number, '#' || NEW.id) || ' is ready for dispatch.',
        'dispatch'
      FROM public.profiles WHERE role IN ('Admin', 'super_admin', 'Dispatch_Officer', 'Manager');
    END IF;
  END IF;
  RETURN NEW;
END;
$func$;

DROP TRIGGER IF EXISTS trg_auto_create_dispatch ON public.orders;
CREATE TRIGGER trg_auto_create_dispatch
  AFTER UPDATE OF status ON public.orders
  FOR EACH ROW
  WHEN (NEW.status = 'Ready for Dispatch')
  EXECUTE FUNCTION public.auto_create_dispatch();

-- 13. Create sync_order_on_delivery function unconditionally
CREATE OR REPLACE FUNCTION public.sync_order_on_delivery()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER AS $func$
DECLARE
  v_has_orders BOOLEAN;
BEGIN
  IF NEW.status = 'delivered' AND (OLD.status IS DISTINCT FROM 'delivered') THEN
    UPDATE public.orders
    SET status = 'Delivered', payment_status = 'paid'
    WHERE id = NEW.order_id AND status NOT IN ('Delivered', 'Completed', 'Cancelled', 'Refunded');
  END IF;
  RETURN NEW;
END;
$func$;

DO $block$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'dispatches') THEN
    DROP TRIGGER IF EXISTS trg_sync_order_on_delivery ON public.dispatches;
    CREATE TRIGGER trg_sync_order_on_delivery
      AFTER UPDATE OF status ON public.dispatches
      FOR EACH ROW
      WHEN (NEW.status = 'delivered')
      EXECUTE FUNCTION public.sync_order_on_delivery();
  END IF;
END;
$block$;

-- 14. Create view for active orders workflow (use dynamic SQL for optional tables)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'dispatches')
     AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'drivers')
     AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'inventory') THEN
    CREATE OR REPLACE VIEW public.order_workflow_view AS
    SELECT
      o.id, o.order_number, o.status, o.payment_status, o.payment_method, o.priority,
      o.total_amount, o.created_at, o.shipping_name, o.shipping_phone, o.shipping_address,
      o.shipping_city, o.warehouse_id, o.driver_id, o.picked_at, o.packed_at, o.dispatched_at,
      p.id AS customer_id, p.full_name AS customer_name, p.email AS customer_email, p.phone AS customer_phone,
      COALESCE(i.quantity_on_hand, 0) AS stock_available,
      COALESCE(i.quantity_reserved, 0) AS stock_reserved,
      CASE
        WHEN i.quantity_on_hand IS NULL THEN 'no_record'
        WHEN i.quantity_on_hand <= 0 THEN 'out_of_stock'
        WHEN i.quantity_on_hand - COALESCE(i.quantity_reserved, 0) <= 0 THEN 'fully_reserved'
        WHEN i.quantity_on_hand - COALESCE(i.quantity_reserved, 0) < 10 THEN 'low_stock'
        ELSE 'in_stock'
      END AS stock_status,
      d.id AS dispatch_id, d.status AS dispatch_status,
      dr.full_name AS driver_name, dr.phone AS driver_phone
    FROM public.orders o
    LEFT JOIN public.profiles p ON p.id = o.user_id
    LEFT JOIN LATERAL (
      SELECT SUM(COALESCE(i2.quantity_on_hand, 0)) AS quantity_on_hand,
             SUM(COALESCE(i2.quantity_reserved, 0)) AS quantity_reserved
      FROM public.order_items oi2
      LEFT JOIN public.inventory i2 ON i2.product_id = oi2.product_id
      WHERE oi2.order_id = o.id
    ) i ON TRUE
    LEFT JOIN public.dispatches d ON d.order_id = o.id
    LEFT JOIN public.drivers dr ON d.driver_id = dr.id;
  END IF;
END $$;

-- 15. Update process_mpesa_callback to use 'Paid' instead of 'Processing'
CREATE OR REPLACE FUNCTION process_mpesa_callback(
  p_checkout_request_id VARCHAR,
  p_merchant_request_id VARCHAR,
  p_result_code INT,
  p_result_desc TEXT,
  p_amount NUMERIC,
  p_receipt VARCHAR,
  p_phone VARCHAR,
  p_raw_payload JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_payment RECORD;
  v_order RECORD;
  v_item RECORD;
  v_callback_id UUID;
  v_is_success BOOLEAN;
  v_payment_status VARCHAR;
BEGIN
  v_is_success := (p_result_code = 0);
  v_payment_status := CASE WHEN v_is_success THEN 'paid' ELSE 'failed' END;

  IF EXISTS (SELECT 1 FROM public.payment_callbacks WHERE checkout_request_id = p_checkout_request_id AND processed = true) THEN
    INSERT INTO public.payment_logs (event_type, provider, description, payload)
    VALUES ('duplicate_callback_ignored', 'mpesa', 'Ignored duplicate callback for ' || p_checkout_request_id, p_raw_payload);
    RETURN jsonb_build_object('success', true, 'message', 'Duplicate callback ignored');
  END IF;

  SELECT * INTO v_payment FROM public.payments WHERE transaction_reference = p_checkout_request_id FOR UPDATE;

  IF v_payment IS NULL THEN
    INSERT INTO public.payment_callbacks (checkout_request_id, merchant_request_id, result_code, result_desc, raw_payload, processed)
    VALUES (p_checkout_request_id, p_merchant_request_id, p_result_code, p_result_desc, p_raw_payload, true);
    RETURN jsonb_build_object('success', false, 'error', 'Payment intent not found for reference ' || p_checkout_request_id);
  END IF;

  SELECT * INTO v_order FROM public.orders WHERE id = v_payment.order_id FOR UPDATE;

  INSERT INTO public.payment_callbacks (
    payment_id, checkout_request_id, merchant_request_id, result_code, result_desc, amount, mpesa_receipt, phone_number, raw_payload, processed
  ) VALUES (
    v_payment.id, p_checkout_request_id, p_merchant_request_id, p_result_code, p_result_desc, p_amount, p_receipt, p_phone, p_raw_payload, true
  )
  ON CONFLICT (checkout_request_id) DO UPDATE SET
    merchant_request_id = EXCLUDED.merchant_request_id,
    result_code = EXCLUDED.result_code,
    result_desc = EXCLUDED.result_desc,
    amount = EXCLUDED.amount,
    mpesa_receipt = EXCLUDED.mpesa_receipt,
    phone_number = EXCLUDED.phone_number,
    raw_payload = EXCLUDED.raw_payload,
    processed = true
  RETURNING id INTO v_callback_id;

  UPDATE public.payments SET status = v_payment_status, updated_at = NOW() WHERE id = v_payment.id;

  -- Use 'Paid' instead of 'Processing' to match the new workflow
  UPDATE public.orders 
  SET 
    payment_status = v_payment_status, 
    status = CASE WHEN v_is_success THEN 'Paid' ELSE status END
  WHERE id = v_order.id;

  IF v_is_success THEN
    FOR v_item IN (SELECT product_id, quantity FROM public.order_items WHERE order_id = v_order.id) LOOP
      INSERT INTO public.inventory_logs (product_id, order_id, change_amount, reason, notes)
      VALUES (v_item.product_id, v_order.id, -v_item.quantity, 'sale', 'M-Pesa payment verified');

      UPDATE public.products 
      SET stock = GREATEST(0, stock - v_item.quantity)
      WHERE id = v_item.product_id;
    END LOOP;

    IF v_payment.user_id IS NOT NULL THEN
      INSERT INTO public.notifications (user_id, title, message, type)
      VALUES (v_payment.user_id, 'Payment Received', 'We received your payment of KES ' || p_amount || ' for Order ' || v_order.id || '. Thank you!', 'success');
    END IF;
  END IF;

  RETURN jsonb_build_object('success', true, 'message', 'Callback processed idempotently');
EXCEPTION
  WHEN OTHERS THEN
    INSERT INTO public.payment_logs (event_type, description, payload)
    VALUES ('callback_processing_error', SQLERRM, p_raw_payload);
    RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;

-- 16. Enable realtime for new tables (wrap in DO block since ALTER PUBLICATION doesn't support IF NOT EXISTS)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'order_status_history'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.order_status_history;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'picking_lists'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.picking_lists;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'picking_list_items'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.picking_list_items;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'packing_lists'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.packing_lists;
  END IF;
END $$;
