import { useEffect, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CreditCard, FileText, Landmark, TrendingUp, Wallet } from 'lucide-react';
import { financePortalService } from '../../services/financePortalService';

const FinanceDashboard = () => {
  const [data, setData] = useState({ invoices: [], payments: [], expenses: [], transactions: [], months: [] });
  useEffect(() => { financePortalService.dashboard().then(result => { if (!result.error) setData(result.data); }); }, []);
  const revenue = data.payments.reduce((sum, row) => sum + Number(row.amount || 0), 0);
  const expenses = data.expenses.reduce((sum, row) => sum + Number(row.amount || 0), 0);
  const outstanding = data.invoices.filter(row => !['Paid', 'Cancelled'].includes(row.status));
  const receivable = outstanding.reduce((sum, row) => sum + Number(row.amount || 0) - Number(row.paid_amount || 0), 0);
  const cards = [['Revenue', revenue, TrendingUp, 'text-emerald-600'], ['Expenses', expenses, Wallet, 'text-rose-600'], ['Outstanding Invoices', outstanding.length, FileText, 'text-amber-600', true], ['Accounts Receivable', receivable, CreditCard, 'text-blue-600'], ['Accounts Payable', 0, Landmark, 'text-violet-600']];
  return <div className="space-y-6"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-600">Finance Portal</p><h1 className="text-3xl font-extrabold">Dashboard</h1><p className="mt-1 text-slate-500">Your finance workspace at a glance.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label, value, Icon, color, count]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800"><Icon className={color} size={22}/><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{count ? value : `KES ${Number(value).toLocaleString()}`}</p></div>)}</div><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-slate-800"><h2 className="mb-4 font-bold">Revenue</h2><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.months}><XAxis dataKey="month"/><YAxis/><Tooltip/><Area dataKey="revenue" stroke="#2563eb" fill="#bfdbfe"/></AreaChart></ResponsiveContainer></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-slate-800"><h2 className="mb-4 font-bold">Expenses</h2><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.months}><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="expenses" fill="#f43f5e" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></section></div><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800"><h2 className="p-6 font-bold">Recent Transactions</h2><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-900"><tr><th className="px-6 py-3">Date</th><th className="px-6 py-3">Description</th><th className="px-6 py-3">Type</th><th className="px-6 py-3 text-right">Amount</th></tr></thead><tbody>{data.transactions.length ? data.transactions.map((row, i) => <tr key={`${row.type}-${row.id || i}`} className="border-t border-slate-100 dark:border-slate-700"><td className="px-6 py-3">{new Date(row.date).toLocaleDateString()}</td><td className="px-6 py-3">{row.description}</td><td className="px-6 py-3 capitalize">{row.type}</td><td className="px-6 py-3 text-right font-semibold">KES {Number(row.amount).toLocaleString()}</td></tr>) : <tr><td colSpan="4" className="px-6 py-10 text-center text-slate-500">No transactions yet.</td></tr>}</tbody></table></section></div>;
};
export default FinanceDashboard;
